### ISSUE TITLE
https

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#100]
We should figure out how to support https, esp. as we develop login/admin

**Comment by LeoTindall** [comment]
Perhaps we can use a self-signed cert for dev and then get a LetsEncrypt
cert at some point

**Comment by huss** [comment]
We have a certificate from Beloit College that should be working with
Apache. I think we need to figure out how to make it work with our web
server software.

**Comment by huss** [comment]
Now that we have users and an admin login, the issues of https is becoming more important. I suspect this has to do with the port we are using as you can do a secure connection to the Apache web server on the same machine. While this relates to our development server, I think it will likely be similar on other Linux systems. Anyone with spare time interested in looking into this?

**Comment by LeoTindall** [comment]
I'd be happy to; I don't have access to the server, but if someone could send me the Apache config I'll look at it

**Comment by huss** [comment]
I want to up the ante on this one. I have now been in two circumstances where people at other places cannot access our OED site. I suspect it is related to not having a good certificate. In one case it was very strange because they could not seem to go to explicit ports but could go to the named site (oed.beloit.edu/demo). I cannot explain why.

**Comment by NoraCodes** [comment]
This is not a problem with the OED software and I think it should be closed here - OED supports HTTPS via reverse proxy, it's just that the main installation's reverse proxy isn't working.

**Comment by huss** [comment]
This is an operations issue on our own server and may become an issue for others. Until we have a way to track OED related issues that are not directly the code we can leave this here.

**Comment by NoraCodes** [comment]
There exists a reverse proxy bug which I am working on. This comment is a note that, when merging Obvius functionality, we need to ensure that we support X-Real-IP for logging, or give up on logging IP addresses.

**Comment by huss** [comment]
This was resolved about a year ago but not closed so here I go.
