### ISSUE TITLE
react-notification-system and react

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1000]
### Is your feature request related to a problem? Please describe.

react-notification-system has peerDependencies of React 16 and less. OED now uses React 17. To fix, installOED.sh added --legacy-peer-deps (see TODO). The issue is that this affects all packages.

### Describe the solution you'd like

react-notification-system does not seem to have updates in the past few years. We should see if they do updates for more recent versions of React. Alternative is to find another package that would work for our needs in OED.

### Describe alternatives you've considered

The hack listed above is what was used.

### Additional context

none

**Comment by Aditya6112** [comment]
If react-notification-system is not actively maintained or does not have a compatible version for React 16, consider exploring alternative notification packages. There are several other notification libraries available for React that might suit your needs and are more up-to-date with React's latest versions. Some popular options include {**react-toastify**}, {**react-notifications**}, and {**react-sweet-alert**}.

**Comment by hyperupcall** [comment]
It seems this has been fixed by e4ca15bc32b875a12d85b1dc0b17e0be49a4c773

**Comment by hyperupcall** [comment]
I also stumbled upon this issue when developing #879, and fixed it with 5ce99352dd1423b6ac0167ca6e83dd3eba659ab2, but that is no longer needed since `react-notification-system` is no longer used

**Comment by huss** [comment]
Thanks to everyone who looked into this. It does appear that OED is not actively using react-notification-system. It seems that src/client/app/utils/notifications.ts is using react-toastify. Thus, I propose we remove it from the code base. Here are the items I know of:

- Uninstall from package.json and package-lock.json.
- Remove all the commented out code involving react-notification-system in code and comments.
- Make sure the comment in src/scripts/installOED.sh about the issue is cleaned up.
- Remove all references to NotificationSystem.
- Maybe something else :-)

The hope is this should be fairly straightforward to finish.

**Comment by spearec** [comment]
As @hyperupcall noted, I removed `react-notification-system` in [e4ca1](https://github.com/OpenEnergyDashboard/OED/pull/919/commits/e4ca15bc32b875a12d85b1dc0b17e0be49a4c773). Looks like I forgot to remove the related `types` package. This was something I had done as part of the React and node update effort, and I never had the time to properly finish after the end of the semester.
