### ISSUE TITLE
Units of type suffix should have a suffix

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1019]
### Describe the bug

Currently a unit can be of type suffix but not have a suffix included and the inverse is also possible for both creating and editing a unit. It does not make sense to have such a combination and an admin should be forced to include both or neither. If a suffix is added but the unit is not of type suffix then the admin should be told the type will be changed to suffix. If the unit is of type suffix but there is no suffix unit then the suffix input should become red and an entry required before saving.

### Screenshots

Examples for create a unit are shown but edit behaves similarly.

![Screenshot 2023-09-25 073325](https://github.com/OpenEnergyDashboard/OED/assets/987062/f50d9f81-8113-472e-af73-13f98e52ecf1)

![Screenshot 2023-09-25 073307](https://github.com/OpenEnergyDashboard/OED/assets/987062/97291f16-16c8-480e-852d-5fb0c031db37)

### Additional context

Currently the admin help warns about doing this so hopefully it will not happen but this fix would mean the documentation can be updated to say it cannot happen.

**Comment by Jake-Bodin** [comment]
I want to work on this issue.
