### ISSUE TITLE
Delete a unit

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1020]
### Is your feature request related to a problem? Please describe.

It would be good if a unit could be deleted as can be a conversion.

### Describe the solution you'd like

If a unit is not used in a conversion, meter, or group then it should be safe to remove. This could be added to the edit unit modal page. We should check for any other conditions where it would be unsafe to delete a unit.

### Describe alternatives you've considered

Currently states can be hidden so no one can use them which has a similar effect to deleting but does not remove them.

### Additional context

As part of this effort, it would be good to remove suffix units created by OED if the suffix is illuminated. Currently, they are made hidden.

**Comment by sparakala21** [comment]
Id like to work on this

**Comment by huss** [comment]
First issue #901 should be done so IDs are not an issue but it may not be an issue since unused.
