### ISSUE TITLE
only get version once

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1048]
### Is your feature request related to a problem? Please describe.

OED displays the version at the bottom of each page. Each time you change pages (to/from graphic page or any other page) it does an api call to get the version. Since the version cannot change except after an upgrade, the version will remain the same so this api call is unneeded.

### Describe the solution you'd like

If there is a version in Redux state then the api call should not be made. The code in src/client/app/actions/version.ts already has a shouldFetchVersion() function so it can be augmented to check for the Redux state.

### Describe alternatives you've considered

OED works fine but this is an inefficiency and not in line with the new way other state is only fetched once.

### Additional context

None

**Comment by Jake-Bodin** [comment]
I would like to work on this.
