### ISSUE TITLE
Slider max should change based on available data

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#110]
When there are only a few weeks or months of data, it's very unhelpful to have up to 365 days on that bar. It should scale from 1 day to the number of days of available data.

This should be easy to implement: Get the length of available data, then set the `max` prop of the `Slider` component to that value (fall back to a sensible value like 30 days).

**Comment by huss** [comment]
Issues #475 and #479 address this in a more systematic way. Their result should be that if you select more days than exist the graph will only show the days you actually have. Given this, I don't think this is an important use case to fix.
