### ISSUE TITLE
avoid file write/read in test data

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1131]
### Is your feature request related to a problem? Please describe.

Currently OED creates data, writes to a file and then reads from the file to associate the readings with the meter. It would be good to avoid the file write/read for the test data for developers and the website.

### Describe the solution you'd like

See above.

### Describe alternatives you've considered

Use the current, slower process.

### Additional context

None

**Comment by kramosss** [comment]
Hi, I would like to work on this issue.

**Comment by huss** [comment]
PR #1233 listed this as partly addressed. It clearly fixed for developer data. The same holds for the website but that is mostly read from data files that cannot be removed. Thus, this is considered closed since done.
