### ISSUE TITLE
ability to copy/see popup message from toast

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1158]
### Is your feature request related to a problem? Please describe.

OED has now converted to using the popups in src/client/app/utils/notifications.ts to show the user messages. The user will want to copy these messages for a record, because they are complex and other reasons. Currently it is unclear how to copy the text. This includes where the message is long so you have to scroll so a screenshot is not a good option.

### Describe the solution you'd like

Be able to easily see/copy message popup text. How or if alternative messaging that is React compatible is needed is unknown.

### Describe alternatives you've considered

There is not a known good alternative at this time.

### Additional context

none

**Comment by rfrost30** [comment]
I would like to work on this! Are there steps to force a popup message to show for testing?

**Comment by huss** [comment]
> I would like to work on this! Are there steps to force a popup message to show for testing?

Any message, esp. one with an error will show this. If you go to the login page and put in bad credentials then one will pop up for 15 seconds. You can get it to stay longer by changing the default autoDismiss for showErrorNotification in src/client/app/utils/notifications.ts. Note that long messages should be able to be copied (not just one line). I also think that lots of message from a CSV upload do not show all lines but I'm uncertain if that is a copy/paste issue or the messages were truncated. If you get it working and need help in getting a very long message then let me know.
