### ISSUE TITLE
add help icon to history arrows

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1159]
### Is your feature request related to a problem? Please describe.

OED now has arrows to navigate graphing history. As usual, OED should have a help icon for this feature.

### Describe the solution you'd like

Add a help icon to the right of the arrows:
![Screenshot 2024-03-21 112041](https://github.com/OpenEnergyDashboard/OED/assets/987062/c818d44e-caee-4585-acd0-729f068a0831)
Note there are no arrows if no history so the icon should also disappear if possible.

### Describe alternatives you've considered

We could add the help somewhere else on the page but that is not consistent with other OED help.

### Additional context

None

**Comment by mikedivine** [comment]
I will tackle this issue.
