### ISSUE TITLE
Plotly capture of graphic image

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1160]
### Is your feature request related to a problem? Please describe.

Before PR #1113, OED included Plotly action icons at the top, right of the graphics. Many were problematic and users were advised not to use them except to capture the graphic as an image. If possible, it would be nice to add only the Plotly icon to capture the graphic image and not any others. If the one with the Plotly version and link is left then that would be okay but not required.

### Describe the solution you'd like

Add icon as described.

### Describe alternatives you've considered

Users can often get screen capture but that is often a less scalable image and requires knowledge of how to do it.

### Additional context

The previous controls can get seen at https://openenergydashboard.github.io/help/v1.0.0/lineGraphic.html where the camera should be the icon to get a graphic image. Issue #1161 addresses differences in the icons for radar.

**Comment by williamw04** [comment]
I'd like to attempt this

**Comment by huss** [comment]
This is solved by the linked PR so it is being closed.
