### ISSUE TITLE
Remove zoom on map graphic

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1162]
### Describe the bug

You can drag to zoom on the map graphic as is possible in line & bar. However, on map it  zooms in on the map and double clicking does not restore the map's size. Given this, zooming should not be allowed. Note it is already disabled for compare.

### Expected behavior

No zoom.

### Additional context

None

**Comment by nlin21** [comment]
I will work on this issue.

**Comment by nlin21** [comment]
Zoom feature works as intended. Additionally, you can zoom out by double clicking (fast) on the map graphic, clicking the back arrow at the top left to go back in history, or by selecting a new meter from the menu on the left. Documentation should be updated.

**Comment by huss** [comment]
Thanks to @nlin21 for working on this and figuring it out. I'll update the documentation. This issue is now done.
