### ISSUE TITLE
values wrong on map graphic based on bar choice

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1163]
### Describe the bug

The dates shown on the map graphic seem to show the correct start date but the end date is based on the bar interval and not the map interval. Furthermore, it seems to normalize the value by the number of bar days not map interval days.

### To Reproduce

1. Select the Sin Amp 1 kWh meter.
2. On map note the values shown or day, week, 4 week.
3. On bar interval select day from what should have defaulted to 4 week.
4. On map the dates are only one day and the values are off.

### Expected behavior

Bar and map intervals should be independent and work properly.

**Comment by danielshid** [comment]
i will be working on this issue.
