### ISSUE TITLE
custom slider on map

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1164]
### Is your feature request related to a problem? Please describe.

Bar has a custom slider for the bar interval. It is unclear why map does not parallel that.

### Describe the solution you'd like

Add add a similar but independent custom slider to the map graphic page.

### Describe alternatives you've considered

Lack the feature.

### Additional context

None.

**Comment by huss** [comment]
PR #1249 converts from a slider to text box. This should be used here and a common component might be desirable.

**Comment by danielshid** [comment]
i will be working on this issue.

**Comment by huss** [comment]
Closed because superseded by #1293.
