### ISSUE TITLE
Chart link button not translated

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1168]
### Describe the bug

The chart link button on the  graphic page is not translated per this image:
![Screenshot 2024-03-22 085914](https://github.com/OpenEnergyDashboard/OED/assets/987062/e245e10c-f6e6-45db-8ebf-d1a244eefccf)

### To Reproduce

1. Go to graphics page
2. Choose a language other than English
3. It will not display in the chosen language

### Expected behavior

It should be translated.

### Additional context

None

**Comment by nlin21** [comment]
I am working on this issue
