### ISSUE TITLE
translate when no map displayed

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1169]
### Describe the bug

"There\'s not an available map" is not translated and in two places in the code.

### Additional context

It might be easy to address this as part of issue #1145 but not necessary.

**Comment by hazeltonbw** [comment]
I will work on this.

**Comment by huss** [comment]
> I will work on this.

Thanks. I'm assuming you are not addressing issue #1145. If you start to touch that then we should communicate since someone else is working on that.
