### ISSUE TITLE
tell user to do page refresh on dashboard error

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1171]
### Is your feature request related to a problem? Please describe.

Since PR #1113, the dashboard catches otherwise uncaught errors and displays a message with a button to return to the dashboard. Sometimes this button does nothing but refreshing the web page works.

### Describe the solution you'd like

Assuming this is not a bug with the button but due to bad state that must be wiped to continue, add below the current button something similar to (and translated):
If the clicking the "Return to Dashboard" button does not work then please click the button below to restart your OED session
<button to refresh; not sure if need to force to initial OED page>

### Additional context

None

**Comment by hazeltonbw** [comment]
I have made changes in our fork that adds a "restart session" button for when users are stuck in an error state. Please assign me to this issue so I can show the changes.
