### ISSUE TITLE
Consistent margin on graphics

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1172]
### Is your feature request related to a problem? Please describe.

Plotly was giving 3D a margin top for some reason. Setting all margins and padding to 0 seems to have fixed it. OED should be consistent about this.

### Describe the solution you'd like

Do for all others to ensure it doesn’t catch us off guard randomly in the future somehow. This assumes this is an okay change and good idea.

### Additional context

None.

**Comment by aduques** [comment]
Can @gyordong and I work on this issue?

**Comment by hinyan17** [comment]
i would like to work on this issue
