### ISSUE TITLE
Groups/meters filter search

### ISSUE THREAD

**Issue by LeoTindall** [OpenEnergyDashboard/OED#118]
Allow a user to filter by a search term. Questions: Should this be fuzzy search? Exact? Allow inter-character variation?

**Comment by LeoTindall** [comment]
A design question: Is filtering desirable, or should matches just be moved to the top of the list with some type of separator?

**Comment by huss** [comment]
I think the search should be one that is standard software and responsive.
Other than that I don't care too much. My first thoughts on what is
desirable are:

   1. Jump to the point in the list that first matches but this requires a
   way to continue to find other ones. If items are not removed from the list
   once chosen then this might be an issue.
   2. Show all items that match (either only those or at the top with
   separator). This allows one to add meters/groups that are similar which I
   suspect may be used. For example, search for smith and you find the meters
   smith01, smithsecondfloor, etc.
   3. Allowing a fancier match is fine but I don't know how common this is.
   I don't think most users would use wildcards. As for close matches with
   spelling-type correcting, this might work but it may confuse people. You
   may see more matches that you don't care about if there are items with
   similar spelling. I'm more inclined toward #2 but don't feel too strongly
   about this.

We can do one and ask users what they think. I would do the easiest one
that we want for the first shot.

**Comment by simonbtomlinson** [comment]
I think filtering is probably the way to go. Searching and getting results that don't match is kind of odd.

**Comment by sandeepacharya464** [comment]
I agree with Simon.

**Comment by LeoTindall** [comment]
In that case, what I implement will be pretty much exactly the same as [react-select-search](https://www.npmjs.com/package/react-select-search). I'm happy to do it but it seems like a better use of time to just use that.

**Comment by huss** [comment]
Since it appears a standard react component will do the basic features of
what we want, I move we do that. It will be fast to implement and allow us
to get user feedback. We can adjust based upon that experience.

**Comment by johndiiorio** [comment]
Implemented into groupsUI with #125.
