### ISSUE TITLE
date range does not include last day

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1182]
### Describe the bug

When you select a date range, the last day is not included in the range. I’m not sure this is intuitive for the user. For example, you select one day (6/1/21-6/1/21) and you get nothing or 3 days (6/1/21-6/3/21) gives two days. I think we should reconsider this behavior.

### Expected behavior

I think OED should include all the dates in the date range for all graphics. Note OED considers midnight of a day (00:00:00) to be the start and this may relate to this issue.

### Screenshots

This show the current way for 3 days showing 2 on a day bar graphic:

![Screenshot 2024-04-03 102005](https://github.com/OpenEnergyDashboard/OED/assets/987062/fa74b685-688c-48bc-8540-306a3a0130a8)

### Additional context

None

**Comment by williamw04** [comment]
I will attempt this issue
