### ISSUE TITLE
refresh data icon on radar graphic

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1184]
### Describe the bug

Only the line, bar and radar graphic pages have the refresh data icon to get new reading data for the specified zoom range. This was originally designed for the line graphic (before RTK). It works reasonably for bar so is fine to keep there. However, when you zoom on radar is changes the y-axis (not the x-axis for dates) so refresh does not make sense.

### Expected behavior

The refresh icon should be removed from the radar graphic.

### Screenshots

Remove the icon in top, right with red box around it.

![Screenshot 2024-04-03 103605](https://github.com/OpenEnergyDashboard/OED/assets/987062/f61f0fbe-274f-4ea3-b203-81df6949d4eb)

### Additional context

None

**Comment by danielshid** [comment]
I will be working on issue #1184.
