### ISSUE TITLE
auto select meter/group when only one

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1186]
### Is your feature request related to a problem? Please describe.

If you go to the 3D page with only one meter/group selected, you must manually click on that item to display it. Note on the map page that OED auto selects a single map.

### Describe the solution you'd like

Select the item automatically.

### Describe alternatives you've considered

Leave as is.

### Additional context

None

**Comment by nneni** [comment]
please assign this issue to me

**Comment by mmehta2669** [comment]
The code looks good, and very clear wit the functionality.  it works and I'm personally not familiar with the nuances of react to determine if there is a better solution.
