### ISSUE TITLE
don't import * unless essential

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1190]
### Is your feature request related to a problem? Please describe.

lodash is often imported as ``import * as _ from 'lodash';``. A few newer places only do the needed items from lodash. OED would like to change to only import what is needed in each file.

### Describe the solution you'd like

See src/client/app/components/LineChartComponent.tsx that does ``import { debounce } from 'lodash';`` as an example of what is desired.

### Describe alternatives you've considered

Leave as is and have extra items available with possible misuse.

### Additional context

None

**Comment by nlin21** [comment]
I will work on this issue
