### ISSUE TITLE
let user know if CSV upload is ongoing

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1193]
### Is your feature request related to a problem? Please describe.

Loading large files via the CSV page can take time. It is unclear to the user that it is ongoing and they should wait.

### Describe the solution you'd like

Other places in OED use bouncing balls to show it is working on something that needs to complete. A similar solution seems good here.

### Describe alternatives you've considered

None other than no indication as OED currently does.

### Additional context

None

**Comment by SalvadorN323** [comment]
My team and I can work on this issue.

**Comment by huss** [comment]
@SalvadorN323  There is a student developer who I discussed this issue with. I should meet with them tomorrow to verify they are working on this. I would hold off until I confirm. I'm sorry that I forgot to mark the issue reserved.

**Comment by huss** [comment]
> @SalvadorN323 There is a student developer who I discussed this issue with. I should meet with them tomorrow to verify they are working on this. I would hold off until I confirm. I'm sorry that I forgot to mark the issue reserved.

@SalvadorN323 The other developer decided to do other work. Thus, it is available to work on. Could you comment on whether you would like to work on this? I'll assign to you if you want to do it. Sorry for this situation and I hope this will help.

**Comment by hinyan17** [comment]
I'd like to work on this

**Comment by huss** [comment]
Since @SalvadorN323 has not yet indicated interest, I'm assigning to @hinyan17.
