### ISSUE TITLE
standardize how graphics get language aware times

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1194]
### Is your feature request related to a problem? Please describe.

Different parts of the code seem to use different methods to get date aware labeling. Two for hover text are:

- src/client/app/components/ThreeDComponent.tsx uses moment (``dateTS.format(moment.localeData().longDateFormat('L').replace(/YYYY/g, 'YY'))``).
- src/client/app/redux/selectors/lineChartSelectors.ts uses ``timeReading.format('ddd, ll LTS')``

There may be other ways in other places.

### Describe the solution you'd like

OED should decide the best way and consistently use that (maybe by centralizing the code).

### Describe alternatives you've considered

Leave as is but the format may vary.

### Additional context

None

**Comment by ianLewis8** [comment]
I want to work on this issue.
