### ISSUE TITLE
convert CSV upload page to React Toolkit

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1198]
### Is your feature request related to a problem? Please describe.

PR #1113 did a lot of the migration to RTK. The CSV upload page still needs to be done.

### Describe the solution you'd like

Convert to RTK as done for other pages.

### Describe alternatives you've considered

Leave as is

### Additional context

It might be good to reconsider the look of these pages. For example, should these be two separate pages for meters and readings now that we can easily add to the menu choice. The look could also be made consistent with the input on newer pages. If this is not done as part of this issue then a new issue should be made.

This issues supersedes issue #887.

**Comment by mikedivine** [comment]
CSUMB Team - Summer 2024 will work on this.

Team member github usernames:
mikedivine, juanjoseguva, rfrost30, Nireves333, hazelcsumb
