### ISSUE TITLE
consistent area calculation for graphics

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1200]
### Is your feature request related to a problem? Please describe.

src/client/app/components/LineChartComponent.tsx uses selectPlotlyMeterData (which then calls selectScalingFromEntity) to normalize by area. src/client/app/components/ThreeDComponent.tsx does it in that component.

### Describe the solution you'd like

OED should try to be consistent in how it does similar work. The area should be done as in the line chart. Other graphics should be checked to see if they do area in this way.

### Describe alternatives you've considered

Leave as is

### Additional context

If any other important differences are found then they should either be fixed or have issues created.

**Comment by hinyan17** [comment]
I'd like to work on this issue
