### ISSUE TITLE
remove unused timezone code

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1207]
### Is your feature request related to a problem? Please describe.

OED used to get client timezone information from Postgres. It now gets it from moment (see src/client/app/components/TimeZoneSelect.tsx). As a result, the old code is not longer used and should be removed.

### Describe the solution you'd like

The old code is in the following files:

- src/server/app.js: defines the timezone routes
- src/server/routes/timezones.js: timezone route; whole file not needed
- src/server/models/Timezone.js: timezone model; whole file not needed
- src/server/sql/preferences/get_all_timezones.sql: SQL for getting DB timezones; whole file not needed

### Describe alternatives you've considered

Leave unused code

### Additional context

None

**Comment by danielshid** [comment]
I will be working on this issue.
