### ISSUE TITLE
meter reading duplication should be drop-down menu

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1208]
### Is your feature request related to a problem? Please describe.

On the CSV page, the reading duplication is a drop-down menu of 1-9. This forces the value to be integral and that should be the case. The meter create and edit pages allow for arbitrary input of values. When not an allowed value, the save does not actually happen to the DB and no error is shown. It is in Redux state but if the page is refreshed it will go back to its old value.

### Describe the solution you'd like

Convert meter pages to use drop-down. 

### Describe alternatives you've considered

Leave as is with issues involved.

### Additional context

None

**Comment by davanmur** [comment]
I would like to work  on this.
