### ISSUE TITLE
don't allow cumulative reset without cumulative on meter

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1209]
### Is your feature request related to a problem? Please describe.

The meter edit and create pages allow the admin to select cumulative reset without also choosing cumulative. This should not be allowed to avoid mistakes.

### Describe the solution you'd like

Either don't allow checking the cumulative reset if cumulative is not checked or determine after clicked, warn the admin and unselect.

### Describe alternatives you've considered

Leave as is

### Additional context

One example of how this is done is in the group create page where the default graphic unit is set to no unit if the selected child meter/group is not compatible with it.

**Comment by mikedivine** [comment]
I'll work on this issue.
