### ISSUE TITLE
unit with suffix has displayable of none

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1210]
### Describe the bug

If a unit has a suffix then its displayable should be none. Currently unit create and edit do not enforce this. This shows it does force the type of unit but not the displayable:

![image](https://github.com/OpenEnergyDashboard/OED/assets/987062/2aff8471-b3ba-4b69-b085-6509e3fb6c8a)

### Expected behavior

Meter do something similar as seen in:

![image](https://github.com/OpenEnergyDashboard/OED/assets/987062/5c4352a7-4e80-48b9-8ed9-f30c1eecf5b0)

and units should warn and set to none.

### Additional context

None

**Comment by danielshid** [comment]
I will be working on this issue.
