### ISSUE TITLE
confirm unit delete

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1221]
### Is your feature request related to a problem? Please describe.

Other pages such as conversion do a final popup check to verify that a delete is actually wanted. The unit page checks that the unit is safe to delete but does not do a confirm with the admin.

### Describe the solution you'd like

After clicking delete, the admin should have to confirm the delete after it is confirmed to be safe.  This is what conversion shows:

![image](https://github.com/OpenEnergyDashboard/OED/assets/987062/a942dbd2-a627-4760-9c81-669fe976766b)

### Describe alternatives you've considered

None

### Additional context

None

**Comment by mikedivine** [comment]
I'll work on this.
