### ISSUE TITLE
graphical display of units/conversions

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1224]
### Is your feature request related to a problem? Please describe.

OED uses a graph to determine the allowed conversions between units. This can add conversions not directly entered by the admin. Given the complexity of the system, it would be nice to allow admins to see a graphic of the units (vertices) and conversions (edges) graph. This information is in Cik. If it was able to group related units, etc. that would be great.

### Describe the solution you'd like

The details are open but maybe the ngraph package used has a related graphing ability.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by huss** [comment]
This branch (https://github.com/nathang15/OED/tree/visual-units) has code to graph dummy units/conversions with D3 (used by Plotly too). It would need to be updated and have the actual OED data used but hopefully is a good start.

**Comment by nlin21** [comment]
I would like to work on this issue.
