### ISSUE TITLE
dropdown for all interval choices

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1292]
### Is your feature request related to a problem? Please describe.

PR #1249 modified the bar interval to be a dropdown menu. Other pages do not do this.

### Describe the solution you'd like

The compare and map graphic pages have similar choices (day, week, 4 week but not custom). They should become dropdown menus similar to bar.

The compare graphic does not have a label/title as does the other ones so this should be added as internationalized "Compare Interval".

### Describe alternatives you've considered

Leave UI inconsistent.

### Additional context

Another PR discusses adding custom interval option and this may be easy to do at this time (if someone wants).

**Comment by danielshid** [comment]
I will be working on this issue.
