### ISSUE TITLE
lose parts of map on narrow screen

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1347]
### Describe the bug

If the screen is narrow (at least relative to height) then the map is clipped so part is not shown. There is no scroll to horizontally move the map over. When it is too short you can scroll.

### To Reproduce

1. Use the standard Happy Place map. 
2. Go to the map graphic page.
3. Select this map.
4. It probably looks fine on a normal monitor. Use the web browser tools to change so it is acting as a narrow screen such as a cell phone. You should see the issue. If you rotate the screen via the tools it is then okay as described.

### Expected behavior

User should be able to scroll as they can vertically.

### Screenshots

![Screenshot 2024-09-25 131808](https://github.com/user-attachments/assets/fa5e2871-2568-47de-bbfc-7746c2190877)

### Additional context

I don't think this relates to the fixed aspect/size of 300x500 in maps that should be generalized at some time. If it is then it will be a bigger task. It is unknown how to fix this.

**Comment by tien-han** [comment]
I'd like to request reserving this issue!

@SageMar @cmatthews444

**Comment by huss** [comment]
@tien-han (@SageMar @cmatthews444) for wanting to work on this. I'm happy to help.
