### ISSUE TITLE
graphs do not resize with window

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#138]
Resizing window generally causes the graph area to resize. If you shrink the window size to the point that options become a button, then click the option button and close the options popup, then resizing the window larger will not have the graph resize. This happened on my version of Chrome but not Firefox. Also note that in Chrome you get a horizontal scroll bar when the window gets smaller but in Firefox you do not. Not sure this is an issue but noticed it.

**Comment by LucasFares** [comment]
When I resize in Chrome everything works as expected. Are there steps to reproduce this bug?

**Comment by johndiiorio** [comment]
This can be reproduced by first starting the window small, navigating to OED, selecting something to graph, then increasing the size of the window.

**Comment by huss** [comment]
This issue is now gone as of Plotly. Unsure if it went away earlier. Some other menu/sizing issues are there and new issues will be opened for them.
