### ISSUE TITLE
remove check for readings unavailable

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1395]
### Is your feature request related to a problem? Please describe.

Before the Redux Toolkit, src/client/app/components/RadarChartComponent.tsx checked for ``readings === undefined`` because the reading might still being fetched. This probably no longer needs to be done. See the TODO in that file.

### Describe the solution you'd like

Remove and test that okay.

### Describe alternatives you've considered

Don't remove code.

### Additional context

None

**Comment by danielshid** [comment]
I will be working on this issue.
