### ISSUE TITLE
radar graphic fails if meter/group not already graphed with line graphic

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#1404]
### Describe the bug

If a meter or group is selected for graphing in a radar graphic when no previously graphed meter or group in a line graphic then the code crashes where the buttons to restart are shown. So far testing has found that what is important is that the line graphic has never had a meter graphed before a meter is graphed in radar. It does not seem to matter if that meter is currently being displayed or not. It also does not seem to matter which meter is selected - even if it is not the ones being graphed in radar. The same behavior is seen in graphing groups. Selecting a meter in advance does not avoid issues with groups and the other way around.

### To Reproduce

1. Refresh the OED page.
2. Go to the radar graphic page.
3. Select any meter/group.
4. The code should crash.

Selecting a meter/group on the line graphic page after step 1 but before step 2 should avoid the error.

Note there are React warning/errors in the console about the order and number of hooks done.

### Expected behavior

The code should not have an error and display the radar graphic as it does when a meter/group is first selected in a line graphic.

**Comment by nmqng** [comment]
Hi, I would like to work on this issue.

**Comment by huss** [comment]
> Hi, I would like to work on this issue.

@nmqng Thanks and I've assigned you this issue. Let me know if you need anything.
