### ISSUE TITLE
master/devel/release + feature branch system

### ISSUE THREAD

**Issue by LeoTindall** [OpenEnergyDashboard/OED#142]
I'd like to propose that we adopt a "moving master" system whereby the master branch isn't expected to be 100% functional. To aid this, we should maintain a "beta" or "devel" branch which is mostly stable and a "release" or "gold" branch which is even with the deployed version on the server (that is, when a merge is made into the release branch, we do a deployment). 

New features would still be developed in separate branches (and hopefully merged quickly).

We could then tie, either manually or using the build automation @johndiiorio and I are working on, the beta/devel branch and the gold/release branch to their respective deployments, so any instances on the Beloit College server would be updated automatically.

**Comment by huss** [comment]
At the last meeting I proposed 3 branches: development, demo & release.
Release is the same as mentioned. Development is code that is under
development but we want to test or show to special collaborators. Demo is
one that is fairly stable and available for comment by others. This is the
way I have been showing the code to others on the server. If it isn't too
much extra work I think this is something to consider but am open to other
ideas.

**Comment by LeoTindall** [comment]
It does impose a certain amount of overhead, but I think it's worth it, since we'll be able to make guarantees about what will work for demos.

I think we should also introduce a front-end manual testing checklist that we go through before pushing to Release.

**Comment by johndiiorio** [comment]
I think we should have a system, but I think having a development, demo, and release branch doesn't quite work for us. I propose that we start tagging our master branch with versions, then keeping our servers updated to proper versions. For instance, the "development" server could be a direct clone of master (patch), the "demo" server could be all new features (minor), and finally having a LTS server (major).

**Comment by LeoTindall** [comment]
I like @johndiiorio's proposal. SemVer is a great standard and instantly conveys all the meaning we need about our versioning.

**Comment by huss** [comment]
I don't care how we functionally implement the idea of three development
levels. Since there has not been any counter feelings, I'm happy to do
tagging. I move we do this to begin getting ready for the upcoming
demonstrations of OED.

**Comment by huss** [comment]
Is this ready to be closed?

**Comment by LeoTindall** [comment]
With the create of the release branch this is complete.
