### ISSUE TITLE
Consistent Error/Exception UX

### ISSUE THREAD

**Issue by LeoTindall** [OpenEnergyDashboard/OED#145]
Currently, the app has very little in the way of error handling. Thanks to #126 we now have a consistent, global mechanism for displaying arbitrary messages to the user. I'd like to have:

1. A consistent doctrine for when we want to spend time preventing users from doing things that are likely to cause errors. There has been some discussion of this re: naming (see #135, for example), but no consensus in the general case.
1. A global exception handling framework, especially implemented for failed API requests, as they are the main point of failure. A user should not ever have to guess at why a chart isn't showing up; error visibility and system status transparency are [major usability features](https://uxplanet.org/golden-rules-of-user-interface-design-19282aeb06b), and it's [important to communicate failure clearly](https://www.nngroup.com/articles/error-message-guidelines/).

(Note also the difference between _errors_ and _exceptions_; errors are things the user does wrong while exceptions are exceptional conditions encountered during normal operation, like network problems).

**Comment by johndiiorio** [comment]
One thing I'd first like to point out is the new Error components in React 16. This could be helpful for what you are trying to do.

**Comment by LeoTindall** [comment]
Yes, I like the way those error boundaries are implemented a lot. Thanks for pointing me in that direction!

**Comment by LeoTindall** [comment]
This is being addressed by #235
