### ISSUE TITLE
Group barchart / linechart compressed readings error when no selected groups have readings

### ISSUE THREAD

**Issue by simonbtomlinson** [OpenEnergyDashboard/OED#153]
The sql is unable to shrink the timestamp range to a range between real start and end timestamps, so it ends up subtracting infinite timestamps and erroring.

**Comment by simonbtomlinson** [comment]
This is actually kind of complicated because the javascript that calls the functions builds lists based on id columns, but those ids won't be present to make an empty list if we just fix this in sql.

**Comment by johndiiorio** [comment]
This was fixed with the addition of the src/server/utils mapToObject function introduced a while back.
