### ISSUE TITLE
bar stacking backward after going to line

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#155]
This seems to be an issue on both the current demo and developer version on our server. If you select a couple of meters the line graph shows. If you then switch to bar it is fine. If you click bar stacking all is fine. Now, if you click back on line it is fine but if you click on bar then it is stacked but the check box for bar stacking is not clicked. If you click it it unstacks the graph. I think the bar stacking state is in the system and remembered but the box is not being updated correctly. The attached screenshot shows the system in the issue state.

![screen shot 2017-10-10 at 7 32 47 am](https://user-images.githubusercontent.com/987062/31386934-2de42b34-ad8e-11e7-9d20-a155845c9cec.png)

**Comment by johndiiorio** [comment]
This appears to have been resolved, possibly with the merge of #148.
