### ISSUE TITLE
contact info on dashboard

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#156]
We should add contact info for the project on the dashboard. We just had someone have trouble reaching us (they are interested in OED :-). I'm inclined to have a link to the website but would consider an email address instead.

**Comment by johndiiorio** [comment]
I think this could be generalized to an About page, which could have:
- Information about the project/mission statement
- Contact info/email address/link to website
- Label of which OED version that is running

**Comment by LucasFares** [comment]
I don't think an about page is necessary; It would just restate what we already have on the website. I think  a footer that links to the website would do what we want.

**Comment by huss** [comment]
I am also inclined to put a link at the bottom that indicates more
information/contact info.

**Comment by johndiiorio** [comment]
This was implemented in #234
