### ISSUE TITLE
Community Guidelines Adherence

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#157]
With (potentially) many more users on the horizon, it's important to think about how welcoming our project is to new contributors. According to [the standard guidelines](https://opensource.guide/), we are [about half way to compliance](https://github.com/OpenEnergyDashboard/OED/community).

Adding a CoC, a CONTRIBUTING file, and issue/PR templates would be trivial, but it's important to talk about whether we want to add them and what we want them to look like.

We should also formulate a plan for identifying "good first issue"s and tag them.

**Comment by LeoTindall** [comment]
Personally, I like the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) (or the [adapted form used by Rust](https://www.rust-lang.org/en-US/conduct.html)) as a CoC. If Beloit College has a ready-made document, we could use that.

Regarding contribution guidelines and issue/pr templates, we need to think about 3 separate groups:

- Bug reporters
- Feature requesters
- Developers

Issue templates are important for bug reports and feature requests by general users, while the contribution guidelines are more important for developers who want to add or edit code.

**Comment by huss** [comment]
There is some info on the web pages about making requests. We should
use/modify as needed. I don't think we want to make users use GitHub to
make requests (though they can).

**Comment by huss** [comment]
I have now added all these items and a developer page about getting started. We have done all the normal items so I consider this complete.
