### ISSUE TITLE
Don't bail out on meter not responding

### ISSUE THREAD

**Issue by LeoTindall** [OpenEnergyDashboard/OED#159]
When reading meters, the system should gracefully handle errors and should still consume data from working meters if one or more are failed.

**Comment by johndiiorio** [comment]
This bug was fixed in #169

**Comment by johndiiorio** [comment]
The system does not handle errors while reading meters properly (such as one line of the CSV is improperly formatted). Thus, I am reopening this issue.

**Comment by jameeters** [comment]
This issue is "Don't bail out on meter not responding". That is, do not bail out on failed network requests.
PR #169 dealt with that problem, so this issue has been addressed and should remain closed.
