### ISSUE TITLE
Should eslint's no-console rule be enabled on the client-side?

### ISSUE THREAD

**Issue by jameeters** [OpenEnergyDashboard/OED#174]
Eslint's `no-console` rule is currently set to `'off'` in the `.eslintrc` in `src/client/`. 
I think that it is a nice rule to have as it stops people accidentally committing log statements used in debugging, so I think it should be set to at least `'warn'`.

**Comment by johndiiorio** [comment]
I think that logging _responsibility_ to the console is a perfectly fine action, and we should not warn when doing it.

**Comment by jameeters** [comment]
That's why you add `// eslint-disable-line no-console` to the line. It seems like an easy way to stop from accidentally committing console logs used in debugging. 

I have no problem with logging to the console, responsibly or otherwise, I just think it's nice to be able to mark the log statements you intend to keep and be warned about the ones you want to throw away. 
I'm not thinking of this as a code-quality problem, just a nice thing that makes it easier to not commit mistakes.

**Comment by johndiiorio** [comment]
Implemented in #188
