### ISSUE TITLE
Disallow cyclic dependencies between groups

### ISSUE THREAD

**Issue by simonbtomlinson** [OpenEnergyDashboard/OED#202]
This is a good first issue for someone with experience in SQL, especially if you know how to write a trigger.

We want to disallow cycles between groups (see the `groups` and `groups_immediate_children` tables). We'll need to create a trigger before inserts to `groups_immediate_children` that throws an error if the reverse relation (the new child is a parent of the new parent) exists in the `groups_deep_children` view.

The relevant sql is in `src/server/sql/group/create_groups_tables.sql`, but you could move the trigger to a new file in that directory if you want. If you do, you'll want to add a function to run your file in `src/server/models/Group.js` and then run that function at an appropriate time in the `createSchema` function in `src/server/models/database.js`.

**Comment by buip** [comment]
This is fixed in #275
