### ISSUE TITLE
website info on release & bugs

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#205]
We should add a tab to the webpages that gives information on each release and any significant bugs that are known. The release information would tell what is new and included along with significant bugs that are resolved. As bugs are found, this would be added for the given release. I realized this partly duplicates the issues and information on the GitHub developers site but I think we need to do this for users. This should be created as part of the the 0.2 release that will pushed out to all sites soon.

**Comment by johndiiorio** [comment]
This is a special case of #156. Also, I think we could link to GitHub issues for known bugs and GitHub releases for major releases. That ensures that users will always have information up to date.

**Comment by LucasFares** [comment]
To be clear, this is a page for https://github.com/OpenEnergyDashboard/OpenEnergyDashboard.github.io?

**Comment by huss** [comment]
First, this is for the GitHub webpages. Second, I still think we should
have it on the web. The vast majority of our users do not use GitHub. I
also think going there is not super easy. First, for issues, you need to
know which ones are important about the release you want. I don't think
that is so easy. I do think it would be good to link to this for anyone who
wants more information/detail. Second, for what is in each major release,
you can look at releases in GitHub but it has very little information. Yes,
you could look at the commits but that is not trivial. While we could put
more in the release info, I don't think that will make it as easy on a
typical OED user. Again, linking to this from the webpage makes sense.
Thus, I still am in favor of us putting this information on a single
webpage. I also note that it gives people a clear picture of what has
happened and where we are going (we could add expected changes in next
release that is now on another page). I think showing we are moving forward
in a clear way is currently important for OED. I welcome the thoughts of
others.

Also, I think we can link more information on future plans so people can
see the work in progress and make any comments they want in GitHub.
