### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by LucasFares** [OpenEnergyDashboard/OED#218]
We need to specify which browser we support. This has far reaching implications for the entire project.

**Comment by johndiiorio** [comment]
I believe we should support support Edge 15+, Chrome 50+, Firefox 52+, and Safari 10.1+.

**Comment by jameeters** [comment]
We can only meaningfully support browsers that at least one of us regularly uses for testing. As far as I know, this includes Chrome (and Chromium) and Firefox. In order to support Edge and Safari, we need to have somebody regularly using each to test the changes.

**Comment by johndiiorio** [comment]
The recent inclusion of Bootstrap 4 requires the browser to support Flexboxes. This is currently the limiting factor on the browsers we support. The browsers previously mentioned all support Flexboxes, and I believe we should specify them somewhere in the README file. @jameeters, @LeoTindall, and @simonbtomlinson, what do you think?

**Comment by corralem** [comment]
Tested OED on these browsers. OED works properly on these browsers. 

Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
Safari Version 13.0.5 (15608.5.11)
Mozilla Firefox Version 76.0.1 (64-bit)

**Comment by LucasFares** [comment]
@corralem Awesome. Thanks for looking into this. [At this point it looks like the majority of browsers support flex boxes](https://caniuse.com/#feat=flexbox) (and given how much the project has changed since this issue was opened I have no idea if that's even a relevant requirement anymore). It may be helpful to list supported browsers over on the [website](https://github.com/OpenEnergyDashboard/OpenEnergyDashboard.github.io) but I'll leave it up to someone else to make that call. At this point,  if browser support hasn't caused a problem in almost three years I think it's safe to close this issue.
