### ISSUE TITLE
Bar and compare charts not working in some cases

### ISSUE THREAD

**Issue by LucasFares** [OpenEnergyDashboard/OED#219]
I have a group AldrichGroup comprised of Aldrich 1st, Aldrich 2nd, Aldrich 3rd, Aldrich Main.

Maurer 2nd, Aldrich 3rd and AldrichGroup (in that order) results in the bug mentioned in PR #215.
However, Aldrich 3rd, Aldrich Ground and AldrichGroup work as expected. 

This affects bar and compare charts. Line charts seem to work in all cases.

**Comment by johndiiorio** [comment]
This issue cannot be reproduced given the steps above. This issue can be re-opened if we can reproduce a bug.
