### ISSUE TITLE
allow admin to specify graphing colors

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#226]
We have a request to allow a site to choose what color goes with each meter and group. Currently we try to guarantee that each meter/group is a unique color and the same each time. We need to discuss how we would do this (need info added to meter/group so related to #211), if we have any protections against reusing colors (people may want to do that), and how we deal with meters/groups without a specified color (and can they repeat or be close to specified colors).

**Comment by johndiiorio** [comment]
Recommend using https://www.npmjs.com/package/react-color to implement color selection/

**Comment by huss** [comment]
Will this be to choose general colors or can someone do it on a meter/group specifically? I can see use cases where someone might want to specify by meter/group such as making renewable production green but I think it adds complexity.

**Comment by johndiiorio** [comment]
This package is only for choosing specific colors.

**Comment by huss** [comment]
This request does not seem urgent and it is unclear it is still wanted by this site. We are working to improve our color selection and keep groups different from meters. This seems a better way to go so this is being closed.
