### ISSUE TITLE
let anyone see what meters/groups are contained in a group

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#239]
We limit access to groups to admins. This makes sense for creating, editing & deleting. However, a regular user cannot tell what meters are included in a group but it seems they should be able to tell. Thus, I think we want to allow a view of groups as admin has without the edit and create buttons for someone not logged in.

**Comment by sandeepacharya464** [comment]
I will work on this.

**Comment by shuheif** [comment]
I believe this is done, so I'm closing this issue.
