### ISSUE TITLE
Inline documentation system

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#259]
We should add small circled-questionmark buttons which, when clicked, bring up inline help for the nearby elements.

**Comment by huss** [comment]
A limited version of this was done for one item. A test of doing across OED was done. At this time we are working on adding real help throughout OED and this is planned to be added after Plotly. One issue that will be trickier is our multilingual support. It will take more work to create the translations for all languages and keep them up to date (the current buttons and minor text is much easier).
