### ISSUE TITLE
email admin on error condition

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#262]
Due to meter issues it sometimes happens that the data acquired is invalid. The meter issue is not caused by OED. A recent change allows OED to read the other meter data for the site and I think it logs the issue. We skip over any new data for the problem meter. Since this is happening with modest frequency and disrupting OED data we should email the admin when it is detected/logged. That way someone knows to look at the issue. We have other places where we are going to want to email the admin so this should be a somewhat general mechanism.

**Comment by NoraCodes** [comment]
I believe we have implemented this, at least in a rudimentary way.

**Comment by buip** [comment]
Yes, we did. I think we can close this issue
