### ISSUE TITLE
URI on date/time stamp error

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#263]
When OED logs an issue with parsing the CSV on meter read, we get a message such as:
[error@2017-12-08T13:01:21.501Z] ERROR ON REQUEST TO [NO URI AVAILABLE], Raw timestamp 00:00:00 0/4</>1 does not pass regex validation
It would be easier to track the problem down if we had the URI. Hopefully we can fix this.

**Comment by johndiiorio** [comment]
Closed in #329
