### ISSUE TITLE
Allow administrator users to reset their passwords

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#265]
Probably via email, as usual. This will require some kind of mail service integration.

**Comment by huss** [comment]
We are in the process of upgrading so we have a user has a role and there will be multiple users. We will be adding a user page under admin to allow an admin to edit user info (email, password & role). This will address this issue and seems a better choice than doing it via email.

**Comment by huss** [comment]
Changing a password probably will not happen often. The new admin user pages (see PR #621) allows one to do this by deleting a user and then recreating. For changing your admin password, you need to create another one, login in as that new admin, delete the other one and then recreate the one just deleted (and can delete the new admin if you want). While this is a little clunky, it was deemed fine given its limited usage.
