### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#266]
The API executes a great deal of code on the server, and could easily be leveraged to cause a DoS condition. We should add:
- [ ] a configurable limit to API access rate, possibly 
- [ ] bypassable with a token available from the admin panel

**Comment by johndiiorio** [comment]
Recommend using express-rate-limit for this purpose.

**Comment by huss** [comment]
PR #633 also has a rate limiting warning from CodeQL that should be fixed.
