### ISSUE TITLE
consistent error string in log file

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#298]
We sometimes have Error: and sometimes ERROR: in the log. We should pick one and make them all consistent (probably by assigning a constant to hold the desired string).

**Comment by johndiiorio** [comment]
If I'm not mistaken, this is due to a recent re-implementation of the logging module. I believe all errors will now be prefixed with "ERROR". However, the error string often contains something like "Error...". Should this still be fixed?

**Comment by huss** [comment]
If we are consistent now then I'm okay with it.  I could check the date
that I saw this but I believe it was Jan. 16. If the change was made and
distributed to sites before then we are probably okay.

I'm not certain I completely understand the exact difference in some cases
but if it starts ERROR then that is enough. Making it as consistent as
possible is always nice but this is a log file that (hopefully) someone who
knows what they are doing is looking at. These small differences are not as
important as possibly missing something due to the case used in the search
depending on the software used to do the search.
