### ISSUE TITLE
bar values wrong

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#312]
If you go to the demo site and select Chapin 2nd, 3rd & student then the sum of 2nd and 3rd should be student. This is what happens in the line graphic. However, this is not the case for bar representations (bar or compare). If you look at bar (say for one week) the sum is off and sometimes it is easy to see since student is less than 2nd and 3rd. If you go to the compare in a 4 week view it is somewhat off and in the week view it is way off. I tried to include the images but it will not work so I will send them around.

**Comment by huss** [comment]
As noted, this did not fix the occasional bar values that are wrong. Anyone working on this should contact me since I have some examples of the problem. Since two different methods for getting the data give issues, the next step might be to see about the graphics package. Since we want to convert to Plotly anyway, maybe we should try that and see if the issue remains. If it is gone then we are done. If it remains then we need to carefully look at the data being used. Anything found should be added to the test suite to catch this type of problem. This is not a target for the 0.5 release but is a priority once that is out the door. I'm going to ask @CorinaSterbet to take the lead on this where helping someone else with it would be fine.

**Comment by NoraCodes** [comment]
I think this is the same as #312 perhaps?

**Comment by CorinaSterbet** [comment]
I looked into the issue and checked the sums of the meter data. For example, one issue stated that, for Maurer 1st, the sum of the day values was different from the week value (for the period Jan 3 - Jan 10, 2019). However, such a time interval does not exist at this moment for the Plotly bar graph. 

The closest time interval that the bar displays is the period Jan 1 - Jan 8. When I check the week interval section, the value for that week is 122 kW. In the day interval section, the sum of the values for each day of the period adds up to 122 kW. Therefore, I could not detect the issue.

**Comment by huss** [comment]
I also checked that groups were the proper sum of their underlying meters. I did not see an issue either. Thus, I'm assuming this is fixed until someone finds otherwise.
