### ISSUE TITLE
Hotlinking to hide chart options

### ISSUE THREAD

**Issue by shuheif** [OpenEnergyDashboard/OED#344]
Add hotlinking option to hide chart options UI as it happens when the screen shrinks. We are not going  
 to have a button for this, but we allow users to manually add something like &hide_options_ui=true to the link. This is to support devices with no mouse, such as digital signage.

**Comment by huss** [comment]
We should verify the status of this and implement anything not yet done.

**Comment by ak476519** [comment]
Currently, if you add "&optionsVisibility=false" at the back of the URL, the redirected page will hide the options accordingly, it works in the same way as the "hide options" button in the left down corner of the default screen.

**Comment by huss** [comment]
This has been done but did not get closed.
