### ISSUE TITLE
Automated Migration Testing

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#366]
Related to #180, #160 . Currently database migrations cannot be tested in a sane way. The workflow is:
- Create a database that is a whole version behind
- Take a database backup
- Write a migration into the current-to-next-version migration table
- Run the migration
- Restore backup
- Repeat

Therefore, it's necessary to make database migrations testable and have automated tests for them.

This is dependent on #364 and #365

**Comment by huss** [comment]
For similar reasons to issue #367, this is being closed.
