### ISSUE TITLE
accepting CSV data via HTTPS

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#370]
There are users who want to directly load a CSV file with meter readings. In this case it is from exporting data from Johnson Controls Metasys. Note this data comes in reverse chronological order with a time stamp that is the end time of the reading and a meter value. We need to make the following changes:

- [ ] Allow user to send the information needed and CSV file via HTTPS. The request will have parameters for user name, password,  meter name, if the data is cumulative or not (not by default), if reading are duplicated and # of times (this may become obsolete) (default of not duplicated), and time interval of each reading (default means calculate from file)

The following are changes that are needed to the current code for importing Metasys CSV files:

- [ ] The previous point's time stamp is the start time for the next point. The last point in the file (oldest in these files) without a previous point will be assigned a start time by subtracting the interval (end - start) of the next to last reading from the end time of this point.  We should warn the admin of points that have different intervals. I propose do this by comparing the current interval to the previous one and warn if it is different. This is a simple and easy method and seems adequate given we don't expect variation unless something went wrong and should not be common. We should not get files with only one point but will do the same technique as the next item for cumulative data to set the interval. If the user provides the interval then this is not done and that value is used. See next item if doing cumulative data since that is also different for the last point.

- [ ] If the values are cumulative then we need to deal with the last point where we don't have a previous point in the file. In this case we will go to the DB to find the closest previous time point and use its value to subtract from the current one. We will also use the difference in time with the DB point as the interval for this point and warn if the time interval is different from the previous one (as usual). If there is no previous value then we should drop this point (this should only happen, in general, if this is the first upload) and warn admin.

Thoughts on this are welcome.

**Comment by huss** [comment]
I have been thinking about this some more and would like to start a discussion about generalizing this feature. The goal would be to accept general CSV files via HTTPS so it would be useful for users that do not use Metasys. 

1. What if we change the parameters so we are told if the meter data in the CSV is in ascending date order (oldest to newest as with MAMAC and some others), descending data order (newest to oldest as with Metasys and some others), or in arbitrary order (if we want to be very general). We could always convert the CSV to the sorted order we determine to be canonical and deal with it that way. Thus, we convert the data to the canonical data stream and then feed it through the OED system via one function/entry point as usual. I think this would allow for any type of CSV that has date, reading as the two columns in the file and would not be much extra work.

1. What if we generalize the interval parameter to allow it to state that there is no standard interval in the data (such as zero or a negative value). In this case OED does not warn if there are differences in intervals and must go to the DB to get the previous point to the oldest one in the file. Basically this suppresses the warnings which might be useful in some circumstances (but riskier for the user if some problem is not reported).

1. I think we should consider removing the duplicate parameter. First, it may become obsolete with other OED changes. Second, this was an issue at a specific site and it is not clear this is general. Thus, unless some sites really want it I think it is best not to add complexity for the user at this time. We can leave the option in the code for now (if easy to maintain) and could add this later if it really is needed.

**Comment by NoraCodes** [comment]
Ideally, the appropriate method for this is to produce a unified ingestion endpoint which we can easily refactor other systems to use. That ingestion endpoint could take optional parameters which the user can use to optimize the ingestion.

For instance, by default we have no choice but to assume the readings are in random order and sort them as they arrive. However, if the user tells us (by optional parameter) that they are sorted or reverse sorted (as in this case) by time, we can bypass sorting and save time.

In this case, having non-uniform intervals is weird, but acceptable. In some cases, it could be normal; in others, unacceptable. This could be communicated by optional parameter (where, in my opinion, abnormal but acceptable should be the default assumption).

Cumulative data should be handled the same way. We don't expect it, but if a user wants to send it, we should have a way to process that.

Fortunately, all three of these are easy to retrofit so long as the code is designed with this in mind.

**Comment by huss** [comment]
We have discussed refactoring the code so all data comes through a common interface. I think this makes both practical and logical sense. OED doesn't really care where data comes from; it only needs a proper set of readings. Having said this, I view it as somewhat orthogonal to this issue. Yes, we may make a common interface as part of doing this but it is for other reasons where doing it then makes sense. Also, this API should then be integrated with other parts of the OED code. Thus, I would like to logically decouple these two items.

As for the rest, it seems we are in agreement. If implementation is easy then lets do the more general cases. I think they will pay off now for others and the long-term. It is also a good example of decoupling accepting meter data and doing validation/cleanup and then passing to on the the API for accepting the standardized data.

**Comment by huss** [comment]
Planning with a site made me realize there is a flaw in what I previously said. It involves the last bullet point in my original post. There I said that if the readings are cumulative data then you go to the DB to subtract the previous value in the DB for the next new reading. The problem is that we don't store the cumulative reading but the usage for that time range. Thus, we don't currently store the cumulative reading so we cannot yet do this. We need to come up with a way to make this work. 

I note that if each CSV only has one point then the original idea of dropping the new point will mean we never store a reading since each time we will not see a previous point in the DB. This needs to be part of the fix and applies more generally to meter streams (such as Obvius) that send a point at a time that is cumulative.

One idea I have to address all of this is to store the newest (in time) time stamp and cumulative reading when it is needed. This could be associated in some way with the meter since we would only store one for each meter. The only failure I have thought of so far is if we get new cumulative data that is not continuing from the most recent data. However, we don't ever expect this and I think we could record an error when this happens (the new time stamp would be before the stored one). The only fix I have so far for this is to store all the cumulative readings but I really don't want to do this when we generally only need the newest one.

I welcome ideas/thoughts as I have only thought about this for a little while.

**Comment by NoraCodes** [comment]
Some thoughts on this, after one failed implementation attempt.

If we accept random-order inputs, we cannot do stream processing, which means we have to throw out the existing `loadFromCsvStream` code and re-implement it with a block/batch processing algorithm.

This is a viable option, and would make solving the cumulative reading problem a lot easier, in that stream processing would have to recompute the cumulative reading base for each streaming window's worth of readings, which would require lots of database access and be very slow, while batch processing would permit computing the cumulative reading base one time, with one database access, and applying it sequentially to all further data.

Even if we prohibit random-order inputs, though, reverse-order inputs will require lots of database accesses or a very good and reliable cache which will be a real pain to design, because every streaming window's worth of data will require a recomputation of reading start and end times. Batch processing would also solve this problem.

Forward-sorted inputs do not have either of these problems. We could simply sort data as it comes in and then pass it in a batch to a slightly modified version of `loadFromCsvStream` which does duration rectification, but that risks blocking the Node.js process (which is single-threaded) for a long time, preventing OED from servicing web requests.

Another option is to create a "shim" service which asynchronously sorts incoming data and then streams it to the main OED server; or, taking this idea to its logical conclusion, we could separate out batch processing tasks into a separate service, which we will probably need to do to handle a large scale anyway, if we ever need that.

I'm working on the first option (sorting data in-process and using `loadFromCsvStream` with some rectification logic), because I expect it to be easy to refactor out the sorting if we decide to do that.

**Comment by huss** [comment]
We are (hopefully) finalizing the new pipeline and obvius integration. The current plan is to use a technique similar to the obvius data acceptance that uses a URL to accept SCV data.

**Comment by huss** [comment]
Note the discussion and design have been moved to a developer document on this topic. Anyone wanting access can request it.
