### ISSUE TITLE
Migrations fail due to baseline trying to create an extension in a non-root context

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#376]
It's impossible to migrate the database from 0.3 to current development because of these lines in the baseline SQL:

```
src/server/sql/baseline/create_baseline_table.sql
6:CREATE EXTENSION IF NOT EXISTS btree_gist;

src/server/migrations/0.3.0-0.4.0/sql/baseline/create_baseline_table.sql
6:CREATE EXTENSION IF NOT EXISTS btree_gist;
```

This is because only role `postgres` can create extensions, and migrations are run as a user. I'm not sure how to mitigate this issue other than running the app as `postgres` which is a terrible idea, or modifying the database creation script and requiring that sysadmins create the extension manually.

More importantly, this highlights the necessity of dealing with #365 and #366 in a timely fashion. Without these problems being solved it is very difficult to administrate the system.

**Comment by huss** [comment]
Unless someone quickly comes up with a way around this, I suggest we manually do this for the handful of sites we will be upgrading to 0.5 in the next week or so. We need to get that upgrade done.

I agree this is an issue that needs to be addressed in a systematic way. Let's make it a target for the next interim release.

**Comment by huss** [comment]
This issue is now very old and no site would do this migration. OED should have a better way to add new extensions on upgrade. It currently works fine on a new installation. Given this is not active I'm going to close it.
