### ISSUE TITLE
Function Capitalization for pgSQL

### ISSUE THREAD

**Issue by kuchtact** [OpenEnergyDashboard/OED#378]
How should functions be capitalized in our pgSQL code. There are many options including all lowercase, all uppercase, and many variant in between. Any ideas would be great. This stemmed from [this](
https://github.com/OpenEnergyDashboard/OED/pull/335#issuecomment-460091048) comment.

**Comment by simonbtomlinson** [comment]
After thinking about it, I usually just capitalized anything that intellij bolded and left the rest lowercase. I think that's pretty reasonable, if only because it looks nice.
