### ISSUE TITLE
Move "Show options" button

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#382]
The "Show options" button shouldn't be hidden in the menu drop-down; users will likely expect it to be visible from the page on which they just clicked "Hide options". It'd be better right next to the menu button or something.

**Comment by huss** [comment]
I'm having mixed feelings about this one given we are trying to conserve screen area. It also serves to focus user attention in some circumstances. Also, we have a new help icon to assist. Given all of this, I'm willing to let this go but others are welcome to input on this issue.

**Comment by huss** [comment]
There was not push to do this so closing.
