### ISSUE TITLE
Better website logo

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#385]
The logo for Open Energy Dashboard appears to read "ED" much more than it does "OED". The program's name should be obvious at first glance. Even something as simple as the attached would be clearer.
![oed_logo](https://user-images.githubusercontent.com/39921639/52546905-aa735c80-2d88-11e9-86e2-a856a7e1759b.PNG)

**Comment by huss** [comment]
The original developers discussed the logo at length. I wanted color but lost on that :-) Given the logo has been used for a while and was voted on by the original development team, I don't think we should change it even if some think it should be changed.
