### ISSUE TITLE
npm run check Cannot Operate on Windows

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#390]
Windows uses backslashes while our scripts are specified with forward slashes. This needs to be fixed, though I'm not sure how.

**Comment by huss** [comment]
Given Windows 10 (non-pro) supports Docker, I think a developer can run the checks via docker-compose. Note there were issues with ** and grep on Macs that are in a similar category with the same proposed solution. Thus, I'm going to close this issue.
