### ISSUE TITLE
The reading values and time labels are mismatched at the bar graph display

### ISSUE THREAD

**Issue by CorinaSterbet** [OpenEnergyDashboard/OED#392]
The meter readings are added to the "datasets" variable in the order received while the dates are being sorted based on the first date of the time interval and only then added to "labels". As a result, the two variables are incorrectly associated when passed as the chart data for display.

**Comment by huss** [comment]
There is already a fix for this that will be coming with the new Plotly graphics.

**Comment by huss** [comment]
As expected, this was addressed when OED switched to plotly  but it was not tagged with that PR. Therefore, this issue has been addressed.
