### ISSUE TITLE
Enforce line length of 80 characters

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#394]
I think we could benefit from requiring new code to conform to an 80-character line length limit, per https://nickjanetakis.com/blog/80-characters-per-line-is-a-standard-worth-sticking-to-even-today

**Comment by huss** [comment]
I'm okay with this but want to be sure we don't force weird line breaks to meet the limit. I don't think we will get code that has stay together and be this long but I wanted to check with people before this is done. If we make it a hard rule (not a warning) then we need to be sure.

**Comment by huss** [comment]
Nothing has happened on this in a long while. Many lines are fairly long due to strings and variable names. It is also the case that monitors now support longer lines without wrap. Developers do not seem concerned about this issue. Given all of that, I'm closing this issue.
