### ISSUE TITLE
Refreshing the groups page takes you to a bad website state.

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#402]
If you go to the Groups page, logged in or out, and refresh the page, you are given a version of the website where no groups or meters are visible. Trying to log in from this state will give you "Failed logging in". Refreshing the website will not fix this, but going to the website again via the address bar will take you to a working website state. This issue is in 0.5 on the live demo server.

**Comment by wendelap** [comment]
Upon further testing, this happens on every page except for Home.

**Comment by NoraCodes** [comment]
I can't repro this; for me, it just places me back at the home page.

**Comment by NoraCodes** [comment]
Still can't reproduce this.

**Comment by wendelap** [comment]
I don't know what caused it, but it works for me now too.
