### ISSUE TITLE
Compare graphs not logging "This Week" data properly

### ISSUE THREAD

**Issue by aaronshirst** [OpenEnergyDashboard/OED#404]
[Compare] graphs (tested with Aldrich 2, 3, Main; seems like more of a programmatic problem) not having 'THIS WEEK' data, breaking functionality of the Energy Usage compare numbers.
	This could be due to an error, or, if data had not yet been added for the current week (Noted on 3:00pm, Sunday 4/14).  If this is the case, the structuring of how we manage data in terms of 'weeks' should be changed to fix this issue.

**Comment by NoraCodes** [comment]
Potentially fixed by #399

**Comment by huss** [comment]
#478 is a more general case of this problem so closing this issue.
