### ISSUE TITLE
Text Issues (Minor issues of typos, readability and scripting)

### ISSUE THREAD

**Issue by aaronshirst** [OpenEnergyDashboard/OED#406]
[Compare] Graphs having a graphical error which causes the [THIS WEEK] text to overlap with This Week's energy usage label.  (Perhaps related to the issue I noted regarding empty THIS WEEK data.

On Front Page, in contact line at bottom, minor type that is easily fixed: "[Contact us] visit [website] for more information." should be changed to "[Contact us] _or_ visit [website] for more information.".

**Comment by NoraCodes** [comment]
Expanded into #422 and #421
