### ISSUE TITLE
Moving custom slider with arrow keys won't update graph.

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#408]
The custom bar interval slider on the bar graph tab can be moved with the arrow keys. However, doing this won't actually update the graph to use the new interval.

**Comment by huss** [comment]
The upcoming switch to Plotly resolves this. If you are on the slider and hit an arrow it causes the graphic to refresh but does not change the bar range. I think it is okay not to have the arrow key move the slider.
