### ISSUE TITLE
User can select a bar interval so short that each bar is less than a pixel wide

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#409]
When the bar interval is set 1 day, either with the button or the slider, the graph is completely blank when it loads. An interval of 2 days works as intended.

**Comment by NoraCodes** [comment]
This is because there are so many days that each bar is less than one pixel wide. Needs some design as to how to fix it elegantly.

**Comment by huss** [comment]
This has, in a way, gone away with our use of Plotly. If you have a graphic with lots of bars then Plotly picks the points to show on a regular basis. For example, it might show one bar and then skip 2. It also does this with the line graph. Thus, I consider this issue closed. A bigger issue is having OED adjust as the window size changes but that is trickier and something different.
