### ISSUE TITLE
French website translation issues

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#410]
The common French term for a website's home page is "Accueil", meaning "welcome". We currently use "Maison" which generally refers to a place where you live.
Month abbreviations and the entire meters page aren't translated to French (and the disable/hide buttons become lowercase for some reason).
In French, the "Select Groups" and "Select Meters" captions on the home page extend over the drop down arrow and look ugly.

**Comment by huss** [comment]
The phrase translation issues were already addressed (PRs did not mention this issue).

Issue #523 addresses the fact that plotly items are not language dependent.

Issue #524 addresses the formatting issue in a more general way.

Given this, this issue can be closed.
