### ISSUE TITLE
Group naming issues

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#411]
When you modify the name of a group, hit cancel, and then go to edit another group, it shows the previously entered name in place of meter's actual name.
When editing a group's name, you cannot backspace the first character or in any way fully empty the text field. This is really bizarre from a user's perspective. Instead, it should let you empty the field and then just give an error like "Group must have a name" when they try to save it.

**Comment by NoraCodes** [comment]
These should be split up into separate issues.
