### ISSUE TITLE
Allow hiding groups

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#414]
It's kind of strange to allow hiding meters from displaying on the website, but not groups. This could probably be added to the large blank space on the right side of the groups page.

**Comment by huss** [comment]
We will need to enhance the group page as part of the generalization planned for 1.0 and this is part of that.

**Comment by huss** [comment]
This is planned to be addressed in a similar way to meters. Groups already have a displayable attribute. The generalization design will hide meters from users if not displayable and the meter page will also be done.
