### ISSUE TITLE
Can't backspace the first character of the group name

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#416]
When editing a group's name, you cannot backspace the first character or in any way fully empty the text field. This is really bizarre from a user's perspective. Instead, it should let you empty the field and then just give an error like "Group must have a name" when they try to save it. (was #411)

**Comment by huss** [comment]
Note issue #496 addresses having an empty name so allowing the remove the current name would be safe once this is done.
