### ISSUE TITLE
Hotlinks do not actually bring the user to the linked page

### ISSUE THREAD

**Issue by Zeewild** [OpenEnergyDashboard/OED#418]
The link from "toggle chart link" does not work.
When "toggle chart link" pasted into new tab no actions (other than default ones) are triggered.
Simply opens fresh OED page.

**Comment by NoraCodes** [comment]
This appears to only happen for bar and compare (e.g. it's working for line). I suspect the reason it fails for compare is related to #403, perhaps the bar failure is related?
