### ISSUE TITLE
Compare graphs text overlap

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#421]
From @aaronshirst: [Compare] Graphs having a graphical error which causes the [THIS WEEK] text to overlap with This Week's energy usage label. (Perhaps related to the issue I noted regarding empty THIS WEEK data).

**Comment by NoraCodes** [comment]
Potentially related to #404

**Comment by huss** [comment]
The change in how we show the compare graphs and going to Plotly means this should no longer be an issue.
