### ISSUE TITLE
Entire app "vibrates"

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#423]
On my 1920x1080 display, the computed width of the app can fluctuate between 1920 and 1912 pixels on a frame-by-frame basis, causing the whole thing to "flicker" rapidly. Observed in Firefox.

**Comment by huss** [comment]
No one has reported this issue in a long while. I tested screen sizes around reported issue using the MDN Responsive Design Mode but cannot see this issue. It seems upgrades and changes have made this go away. I'm closing but someone can reopen if they see it again.
