### ISSUE TITLE
MINOR: Mouse-over graph pop-up gives unpleasant floating point #

### ISSUE THREAD

**Issue by aaronshirst** [OpenEnergyDashboard/OED#426]
Not a bug, but rounding the numbers to a standardized decimal place is a simple change that would go a long way in improving the overall look of the site.  My recommendation would be no more than three decimal places, as opposed to the 14 currently in place.  
 ie
3.153
as opposed to 
3.15277777777778.

**Comment by LucasFares** [comment]
Closing as this issue was fixed in Pull request #435 .
