### ISSUE TITLE
MINOR: Rename "Hide/See Options" to "Hide/See Menu"

### ISSUE THREAD

**Issue by aaronshirst** [OpenEnergyDashboard/OED#427]
I recommend this because when you select the option to "Hide options", the new button that pops up in the top right corner of screen is "Menu".  In selecting between the two, "Menu" feels like a better fit for what is represented on screen, and not having the consistency there gives users opportunity to get lost or confused on the website.

**Comment by huss** [comment]
As OED has added more buttons at the top, it is less clear what menu means. I'm not sure which option is best. However, we now have a help icon to explain what happens. Given all of this, I'm going to close this issue.
