### ISSUE TITLE
chart link does not support Plotly sliders

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#456]
The switch to Plotly allows the user to change to date range displayed on graphics. The chart link URL does not provide these dates. We need to add that and also have the system respect the new parameters in the query string.

**Comment by ak476519** [comment]
The line chart is fully respected by the URL after the commit caa6109e7624c1ad0bee2b20aa8f9c91cf48c8e4 in #455 .

**Comment by ak476519** [comment]
However, there is a bug that we haven't resolved yet that's interfering with the regeneration of the bar chart through the URL. The bug seems to exist before Plotly was integrated. We are still working to find its origin.

**Comment by ak476519** [comment]
> However, there is a bug that we haven't resolved yet that's interfering with the regeneration of the bar chart through the URL. The bug seems to exist before Plotly was integrated. We are still working to find its origin.

The bug is gone after a recent package update in the master branch.
