### ISSUE TITLE
Bar graphs not working with groups or compare

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#461]
Groups do not seem to appear in bar or compare graphs. This appears to be present in version 0.5 (at least for bar graphs) so it is unclear when this happened. It is also unclear if the issues are related for the two types of graphs.

**Comment by ak476519** [comment]
Narrowed down the problem to bar graphs not working with compare, the groups are fine by now.

**Comment by huss** [comment]
Works as expected given issue with compare that is separate from this.
