### ISSUE TITLE
vertical resizing of window does not scale OED display

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#466]
If you horizontally scale your browser window then OED scales with it. If you do it vertically it does not. It would be nice to avoid having to scroll to see graphs and to allow them to get bigger. There could be a minimum size we support (but we don't seem to do that horizontally). I also don't know how this will impact graphic ratio and if it will look okay.

**Comment by sasankthapa** [comment]
https://community.plotly.com/t/plot-sizing-problems/1620 tells us that the plotjs component, when set to "autosize:true" will fill the whole graph div. The height of the div should be set to auto, width is set to 100%. The latest version of bootstrap didn't fix this issue.

If you set {{ width:'100%',height:'100%' }} to the container div then the graph fills vertical height, but only fills the space when you drag the browser.

A potential fix would be to dynamically setting and changing height by adding it to the state.

**Comment by huss** [comment]
Fixed by PR #1113 so closing.
