### ISSUE TITLE
Message in console on OED load

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#471]
When you start OED as a developer and look at the console in the web browser you see a message about a `<div>`. Should decide if it is important and fix if needed.

**Comment by huss** [comment]
We have other warning that are coming out when you load and do operations. They all should be looked into.

**Comment by huss** [comment]
Also, we should review from of the log files to see if there are any messages there to deal with.

**Comment by huss** [comment]
Someone earlier tried looking at this but did not figure it out. They felt one of the messages was discussed in https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html#changes-in-detail.

**Comment by ngan-cassie** [comment]
Warnings about componentWill.. are likely due to some react libraries like react-select, react-dom, react-redux not being up-to-date. Upgrades might be needed to fix the warnings.

**Comment by huss** [comment]
All of these issues are now gone so I am closing this. There are occasional messages but the code generally notes the issue.
