### ISSUE TITLE
Plotly axis vs meter time endpoints

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#472]
fast-pt now shows day averaged data in many circumstances. It does not include partial days at the start/end of the meter day and that makes sense. Plotly displays the time as somewhere (currently start of day but proposed to be middle of day) on a line graph. As a result, the x-axis on a line graph only includes the dates within the range returned by fast-pt. When you zoom in on the start/end of the line graph, you cannot get to any points that are beyond what fast-pt provides even though that meter data does exist. A fix might be to make the x-axis range be the min/max dates stored for a meter so you could zoom into these times (but no points would be in the new range until you redraw). If we do this we need to verify that the DB is optimized to quickly find the min/max.

**Comment by limh0228** [comment]
See if the meters redux state knows anything about the range of time? If not, add a prop like this, and a related database query will need to be written.

**Comment by limh0228** [comment]
Work on this issue has been stalled by a possibly related bug described in issue #642. I couldn't figure out if the two bugs were related, and #642 was obfuscating results when trying to work on this issue. I recommend solving 642 first.

**Comment by huss** [comment]
Just so this is up to date, OED now does daily, hourly and original/raw meter values. The x-axis date/time stamp has been changed to be in the middle of the average range and not the start. The basic issue is the same with these changes.
