### ISSUE TITLE
set checks in pipeline

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#511]
This relates to the merging of PR #482. The conditionSet is undefined in insertMamacData, insertMetasysData & insertObviusData. We need to decide what to put in for these so we actually do testing on inputted data. This may require new admin input to decide.

**Comment by huss** [comment]
The starting point for the code can be found in:

- MAMAC: src/server/services/readMamacData.js
- Metasys: removed from OED and now done via a CSV upload
- Obvius: src/server/services/obvius/loadLogfileToReadings.js
- The pipeline starts with src/server/services/pipeline-in-progress/loadArrayInput.js where the conditionSet controls the tests done.

The tests would be controlled in two ways:

1. For each meter. This will include an option to disable checks on this meter.
2. At the site level on the admin page. These values are used if the meter value is not used and checking is enabled for the meter.

Note that the CSV uploads (either via web page or parameters to an http request) allow for control of many settings that can either use or override the meter setting. This would be a good addition to include (src/client/app/containers/csv/UploadCSVContainer.tsx has the actual selections and should help find how the choices are used).

**Comment by TrongQuocLe** [comment]
@codehomie1 @carlsonrob We're part of CodeDay Labs and we're actively working on this issue.

**Comment by huss** [comment]
> @codehomie1 @carlsonrob We're part of CodeDay Labs and we're actively working on this issue.

I'm happy you are working on this issue for OED. I have added the assigned label so it is easy for others to see you are working on it. Please let me (or the project) know if we can help in any way.

**Comment by carlsonrob** [comment]
@huss 
> I have added the assigned label so it is easy for others to see you are working on it. 

Thanks for that. We are excited to work on this project.

We originally had the problem described as follows:
> ### Pipeline checks
> The OED reading acquisition pipeline allows for admin specified checks on the data. For example, it can detect when a reading is out of range (too small/large). We need to add an interface that allows the admin to set the desired values for checking and then have those values used in the pipeline. There are two ways to set the values used: 1. For each meter. This will include an option to disable checks on this meter. 2. At the site level on the admin page. These values are used if the meter value is not used and checking is enabled for the meter.

Would this issue also entail creating a user interface on the frontend in React to let the admin set these values?

**Comment by huss** [comment]
Yes, we ultimately need the admin interface to set the values. Since this issue was created, the meter page is much more extensive so this would be another option on that page (and on the admin preferences page to create the default values). Note that PR #958 will change how the meter page (and some others) look so it will now be two column. I wanted you to know because that is likely to be done soon and would be the starting point for future changes to the meter page. This was a good question so thanks for asking and let us know if you have anything else.
