### ISSUE TITLE
update packages

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#548]
After we finish version 0.7 we need to systematically update our packages.

**Comment by huss** [comment]
PR #653 updated a lot of the packages that could be done easily. It is left to update others that may require careful checking and code changes due to the nature of the updates in these packages.

**Comment by jina2k** [comment]
As mentioned in #734 , we should update react-router v5 to v6 if/when it becomes backwards-compatible for seamless upgrading. 
react-notification-system could also be switched out. Suggestions are https://www.npmjs.com/package/react-notifications and https://github.com/fkhadra/react-toastify
ESLint should be extended into lint checking src/server in the future as well.

**Comment by huss** [comment]
The work by @jina2k has us up to date on most packages and addressed the issues from 0.7.0. I'm closing this issue but we all know that we will need to continue to update packages as time goes on.
