### ISSUE TITLE
internationalize strings on maps

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#574]
Some strings are not internationalized for maps
- [x] All on the create map page
- [ ] popup on page when upload complete on create map page
- [x] all on calibration page
- [ ] on map page: the word "edited" added to first column when a change is made
- [ ] popup to confirm delete of a map
- [x] map button for map page and map button for graphic type on main page

**Comment by patrick9958** [comment]
Hi Steve (@huss),

Just a quick update. Nicole and I just finished the first and third bullet point. We are running the test suite and we're thinking of submitting a pull request tomorrow :)

Best,
Patrick & Nicole
