### ISSUE TITLE
groups sometimes fail to show up

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#579]
This is a little tricky to see. It only seems to happen for some groups when the meter and group overlap in the sense that the meter is in the group. It does not happen for all groups of this type and, so far, it has only been for one of the meters of this type. When it does happen, the group is not displayed on the bar graphic. It does not seem to matter if you add other meters but it seems important that you choose the meter first or the group that is already displayed remains. You can remove any meter other than the special one and the group does not show. However, as soon as your remove that meter from graphing the group reappears no matter when in the process of removing the meters it happens.

**Comment by jina2k** [comment]
Recreated bug doing the following:
1. Create a group with a meter matching this new id (ie; test4HourSin having an id of 4, with 3 created groups within database already). This means the new group being created will have an id of 4, matching test4HourSin
2. Display bar readings, and then choose test4HourSin to display as a meter.
3. Select the group that was newly created, and it does not display.
4. Somehow if you remove the meter, and then add it in again it fixes itself, which is strange.

Fixed the bug in the following pull request #657 by changing barReadings.ts and compareReadings.ts to have .byMeterID[groupID] changed to .byGroupID[groupID]. This can be seen when following the above steps, where the group successfully displays after the change. (step 3)
