### ISSUE TITLE
automatic site backup

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#590]
We have a shell command to backup a database by using:
`sudo docker-compose exec database pg_dump -U oed > /home/eddy/Database_Dumps/<site name>/dump_$(date +%Y-%m-%d"_"%H_%M_%S.sql)`
It would be nice to have a script provided by OED to do this so it could be put into a cron job to happen regularly. Would also want it described somewhere on the admin and/or install pages.

**Comment by huss** [comment]
PR #759 proposed a solution to this issue and is a good start. It was closed since it was not completed. Someone needs to make the needed edits so it can be merged.

**Comment by vladoleksiyenko** [comment]
Hi, would it be possible to work on this issue?

**Comment by huss** [comment]
> Hi, would it be possible to work on this issue?

@vladoleksiyenko You are welcome to work on this. Please let me know if you need anything.

**Comment by vladoleksiyenko** [comment]
Our team will work on this issue
We'll follow up with any questions that we have at a later time.
Group: @vladoleksiyenko, @MattMiss, @brandonviorato, @gene7him

**Comment by vladoleksiyenko** [comment]
Markdown file of the cron template documentation
Needs to be added to the website.

[OEDBackupScriptTemplate.md](https://github.com/user-attachments/files/18071349/OEDBackupScriptTemplate.md)
