### ISSUE TITLE
easier way to find all meters in a group

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#591]
The group page allows people to see the meters and groups that were added to when the group was created. However, a typical user may want to know all the unique meters that are part of a group to see what is being included. If a group contains groups then you have to recursively check out each group to figure this out and then remove duplicates. It seems a good idea to list them for the user. This does not need to be fancy; a text list on a line would be fine.

1. The first step to see how to get this information from the DB. OED likely has this ability already. @wadoodalam is looking into this.
2. Need to add the info to the group page.

**Comment by wadoodalam** [comment]
The JS code for DB ability to show unique meters in a group is located in models/Group.js in the method name is getDeepMetersByGroupID

**Comment by huss** [comment]
Looking at src/client/app/containers/groups/GroupViewContainer.ts and src/client/app/components/groups/GroupViewComponent.tsx may be good starting point.
