### ISSUE TITLE
figure out TODO items in code

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#592]
The OED code base has TODO comments. We need to find them all, see if they are important, see if issues exist as appropriate or they need to be created.

**Comment by Mushmou** [comment]
Hello Team L from CTI would like to work on this issue.

**Comment by Mushmou** [comment]
@huss Our team developed a plan to capture all TODO comments onto a google doc and were going to determine if the TODO comments need to be turned into an issue.

**Comment by huss** [comment]
Ok. Thank you for taking this on. I'm sure there is quite a range of them so any progress would be good. The project can also help with making issues if that would help.

**Comment by Mushmou** [comment]
@huss How do you want us to turn it in? would a pdf or document be good ? Or would you like us to make a PR to this issue.

**Comment by huss** [comment]
Thanks to @Mushmou and their team for doing this so quickly. If you can give the link to the Google Doc in the issue then the project can put it in any needed format and remix with other documents for getting the work done.

**Comment by huss** [comment]
I realized I don't have a record of the list. Is it possible to get the list and/or a link? Thanks.

**Comment by huss** [comment]
Noting that this issue is still open and not real progress has been made.

**Comment by MattMiss** [comment]
My team would like to take on this issue if possible. Other members include @vladoleksiyenko @Gene7Him and @brandonviorato

We can continue with the same plan of creating a google doc to list each of the TODO's and any other helpful info if one hasn't been created yet.

**Comment by huss** [comment]
> My team would like to take on this issue if possible. Other members include @vladoleksiyenko @Gene7Him and @brandonviorato
> 
> We can continue with the same plan of creating a google doc to list each of the TODO's and any other helpful info if one hasn't been created yet.

Sounds good. Let me know if I can help.

**Comment by MattMiss** [comment]
@huss  We've found/documented most of the 160 TODO comments in the codebase, noting whether each one needs an issue, has an issue, or is related to an existing issue. Before we finish, I’d appreciate any feedback you have to ensure we're on the right track. 

Also, when everything is looking good, would you prefer we keep and share this as a Google Doc, or would you rather us convert it to an MD file than can be added to the project and accessed by anyone? 

[TODO Comments google doc](https://docs.google.com/spreadsheets/d/1LaU3EjlJtHt56qvXnRxf2FcCCKI9-3jaMDYESTsvP3U)

**Comment by huss** [comment]
First, thanks to @MattMiss, @vladoleksiyenko @Gene7Him & @brandonviorato for doing this. Overall, the document looks great and this is a big help.

> @huss We've found/documented most of the 160 TODO comments in the codebase, noting whether each one needs an issue, has an issue, or is related to an existing issue. Before we finish, I’d appreciate any feedback you have to ensure we're on the right track.

It seems great to me and I don't have any suggestions.

> Also, when everything is looking good, would you prefer we keep and share this as a Google Doc, or would you rather us convert it to an MD file than can be added to the project and accessed by anyone?

I think creating a new design doc for the open TODO items would be great. You can clone that repo, make the needed changes and then put in a pull request for the changes. I could do it but I think it might be best for the team so it is publicly under your GitHub IDs since you did the work.

On mechanics: Do you have an automated tool to convert a Google Doc to markdown? I have a Google Doc extension that does a decent job, in most cases, of giving a good first shot that can then be cleaned up. Let me know if you want info or have me give it the first shot.

Please let me know if I can help in any way and many thanks. Once this is done, I think the issue will be ready to close.

**Comment by MattMiss** [comment]
Thank you for your input and tip on the google doc extension. I converted our document into a markdown file and formatted it a bit, then made a Pull Request with the new markdown file here: [https://github.com/OpenEnergyDashboard/DesignDocs/pull/4](https://github.com/OpenEnergyDashboard/DesignDocs/pull/4). 

Feel free to make any changes or let me know if there is anything else you would like done with this.
