### ISSUE TITLE
data range on line graphics

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#594]
OED went to a system that averages to a daily level to speed up OED (fast-pt). Users can zoom in to see raw data but it can be tricky to know where interesting values are located. To help, OED could add "error" bars to points to represent the range of data for the time interval for each point on the line graph. An easy idea is max/min value. Slightly more sophisticated might be 25/75% quartile labels. Something else would be okay too. The idea is it should be fairly fast (certainly for max/min) if we precalculate when do refresh readings of the daily value table. It would give an idea of the underlying range of values for each point. With the new Plotly zoom and redraw feature you could look at areas of concern with greater resolution. This should be an option that the user can turn on since most will not what to see this.

**Comment by huss** [comment]
For now, doing the min/max seems best since we are trying to indicate where values deviate from the average displayed. Also, OED now precalculates both daily and hourly points so both would need the new values. I would not make sense to show these values after the hourly points since OED now shows the original/raw meter data.

The following steps would need to be done:

1. The database functions for min/max need to be added. See src/server/sql/reading/create_compressed_reading_views.sql for how the averages are found. We may be able to do the max/min faster than doing them from scratch and some ideas for the code exist.
2. Need to add a checkbox on the line graphic page so the user can decide if they want to see the max/min values on the graphic.
3. The error bar of min/max needs to be added to the line graphic when it is selected by the user.

**Comment by huss** [comment]
We need to decide how to deal with missing data. Currently OED averages the data present if there is some in the range of time. Would the max/min be of the values averaged or include the missing ones (maybe as a zero value for min)?

**Comment by huss** [comment]
PR #883 did the DB changes but did not add the values to graphics. Therefore I am reopening this issue.

**Comment by huss** [comment]
Groups are problematic since the underlying meters can have different reading frequencies. For the same reason you cannot export a group as raw readings, OED will not show error bars on groups. This feature will only be for line meter readings.

**Comment by JesseVarGar** [comment]
Elias and Jesse are working on this

**Comment by huss** [comment]
> Elias and Jesse are working on this

Great. Please let me or the project know if we can help in any way.
