### ISSUE TITLE
enhance data export

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#599]
OED just added the ability to export raw meter data. As part of that and checking out all exports, I want to request some changes:

- [x] Either export (graph or raw) only gives the start time of each point. We have the start and end time in the DB. The upcoming plan is to allow import with start/end time and this is better since gaps can be seen. I think we should change this for raw and, if not too hard, for the graph as well. We should verify that the exported data can be read back into OED with the new import features.
- [ ] 2. The export puts the unit on each point. This makes it hard to easily graph the spreadsheet in a standard program. Once we do resource generalization the unit may vary by meter so it is needed. I propose we put it as a separate column unless a better idea is found. We should then verify that the way we put out dates does not cause any issues in graphing in a spreadsheet.
- [x] src/client/app/utils/exportData.ts has 5/25 MB file size hard coded (TODO markers in file). Need to make it under admin control with these as the default values.
- [ ] The raw export does not support groups. My first thought is it would dump all the underlying meters since you cannot aggregate the data without averaging if points are not perfectly aligned in start/end time. See if everyone agrees and then do what is decided.

**Comment by LukeLavan** [comment]
#563 removes the `kW` from the exported CSV files. I add a TODO comment where they used to be and specify that in the future the units should be its own separate column when that information becomes available on the `ExportDataSet` and `RawReadings` interfaces.

**Comment by huss** [comment]
Groups do not export raw. That was the final decision.
