### ISSUE TITLE
Internationalization Support

### ISSUE THREAD

**Issue by LucasFares** [OpenEnergyDashboard/OED#60]
Look into adding internationalization support to the software.

**Comment by LeoTindall** [comment]
A relevant blog post about using frontend gettext: http://blog.arkency.com/2015/03/use-your-gettext-translations-in-your-react-components/

**Comment by johndiiorio** [comment]
Add the Admin panel label as admins should be able to set the default language.

**Comment by johndiiorio** [comment]
Implemented in #324
