### ISSUE TITLE
lose selected meter when go to map

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#600]
### Issue

Selecting meters that cannot be shown on the map before selecting a meter on the map graph causes them to stop being graphed.

### To reproduce

1. Select a meter on any graphic type page other than map (line, bar, compare) that cannot be displayed on the map.
2. Go to the map graphic page.
3. Select a meter that can be displayed.
4. Go back to another graphic type page and only the meter that was shown on the map appears and the other meter is gone.

### Note

If you select these two meters before going to the map page then they remain. The critical step appears to be selecting a meter while on the map page. Also, groups are not impacted but that may be because we currently cannot graph them on maps.

### Expected behavior
Selected meters on any graphic should remain even if they cannot be shown on another graphic.

**Comment by jina2k** [comment]
Attempted to reproduce after changing code with pull request #657 
Steps taken:
1. Select a meter on line/bar that cannot be displayed on an example map
2. Change to map display instead of line/bar and select the map that was chosen above.
3. ^Actually step 2 ends up removing the meter so this shows that the issue is still there, before continuing onto selecting another meter.

**Comment by huss** [comment]
I think the meter is still there in step 3 but is grayed out as expected since it cannot be shown on the map. If you select another meter then when you go back to link it is not there. The desired behavior is that selected meters  would be grayed out on maps if cannot be shown but would still return when you go to a different graphic. We will have to figure this out later (not a high priority since unusual and does not mean the user cannot see what they want with extra effort).

**Comment by huss** [comment]
See PR #718 about how this bug is gone but the menus are not working quite as we would like.
