### ISSUE TITLE
Energy cost from Utility

### ISSUE THREAD

**Issue by LucasFares** [OpenEnergyDashboard/OED#61]
Interpret the data in terms of cost.

**Comment by panicalilm** [comment]
What we have completed:
Added UI elements in UIOptionsComponent to changes options for whatever
Added dispatch in UIOptionsContainer to dispatch Redux actions
Added event handler bound to elements to call function from UIOptionsComponent
Added Redux actions 
Added Redux reducers

Still Needs to be done:
Still need to figure out function/constant and and how to relate this to the readings.
In Line/BarChartContainer, get new state value and update data heading to Bar/Line wrapper.

**Comment by huss** [comment]
I'm not sure this will happen with the DB work. Calculating cost could be done in an easy but less precise way or more carefully. I would prefer to keep this open until we get it right.

**Comment by huss** [comment]
We now plan to add this as part of resource generalization. Hopefully it will make 1.0.

**Comment by huss** [comment]
Resource generalization in devDocs has an extensive description of how this will be done and it is already well under progress. This will allow a constant cost for any resource. A different issue is when it varies by time of day or changes periodically. That will be dealt with in the future.
