### ISSUE TITLE
Homepage 'Bar Interval' options messes up tooltip placement in Spanish

### ISSUE THREAD

**Issue by limh0228** [OpenEnergyDashboard/OED#611]
### Describe the bug

When the homepage is loaded in spanish, the tooltip buttons under the 'Bar Interval' options on the left side of the page get moved into messy and unintuitive positions.

Here's how they look in english:
![image](https://user-images.githubusercontent.com/16940652/111917417-4850af80-8a56-11eb-9dac-7df3193b85ea.png)

Here's how they look in Spanish:
![image](https://user-images.githubusercontent.com/16940652/111917430-5f8f9d00-8a56-11eb-9b0c-5a8d389ec911.png)

### To Reproduce

1. Go to the homepage (by clicking on the lightbulb)
2. Click on the Language dropdown under the options on the left side of the page
3. Scroll down to the 'Bar Interval' options

### Expected behavior

The way the tooltips appear should be unified between the languages. French looks a little different from English, but still readable. The spanish config is for some reason really messy,

### Screenshots

Here's how they look in english:
![image](https://user-images.githubusercontent.com/16940652/111917417-4850af80-8a56-11eb-9dac-7df3193b85ea.png)

Here's how they look in Spanish:
![image](https://user-images.githubusercontent.com/16940652/111917430-5f8f9d00-8a56-11eb-9b0c-5a8d389ec911.png)

### Machine info (please complete the following information)

 - OS: Windows 10 Home
 - Browser & Version: Chrome 89.0.4389.90
 - OED Version: 0.6.0

**Comment by huss** [comment]
Changes means this is not seen in Spanish on larger screens but does happen in French.  Smaller screens have this issue in different languages. The larger question is now to be more dynamic with the placement of all items by screen size.

**Comment by huss** [comment]
This is no longer happening. The tooltip ? does go to another line in some cases but this is true for all of them on a smaller screen.
