### ISSUE TITLE
Y axis label overlaps y axis values when zoomed in on graph

### ISSUE THREAD

**Issue by limh0228** [OpenEnergyDashboard/OED#616]
### Describe the bug

When the homepage is loaded normally (without data in my case), the graph looks like this:
![image](https://user-images.githubusercontent.com/16940652/112771741-604aa500-8ffb-11eb-8ff1-0322b5830561.png)

When you zoom in on the graph vertically, the y axis values change to represent the zoom:
![image](https://user-images.githubusercontent.com/16940652/112771781-8ec88000-8ffb-11eb-96fe-ddd7d45f6f17.png)

However, if you zoom in even more vertically, the y axis value strings become too long, and overlap the y axis label:
![image](https://user-images.githubusercontent.com/16940652/112771823-b9b2d400-8ffb-11eb-9ad9-500b00652837.png)

### To Reproduce

1. Go to OED site homepage
2. Click anywhere on the graph, and hold and click while dragging cursor downward or upward. This should zoom in vertically on the graph.
3. Do this a few times until the bug is revealed.

### Expected behavior

Here are a few ways to approach the problem. When the y axis values get too small to abbreviate without losing clarity, we can:
- allow the graph to resize and push itself out to the right to make room for the y axis values or
- make the y axis values have a smaller font so they fit in the intended space

### Screenshots

(See above for screenshots)

### Machine info (please complete the following information)

 - OS: Windows 10 Home
 - Browser & Version: Chrome 89.0.4389.90
 - OED Version: 0.6.0

### Additional context
N/A

**Comment by huss** [comment]
I've seen other weird behavior on empty graphs such as nothing happening on redraw if zoom in too far. I think the bigger issue is what we display on an empty graphic. Issue #576 proposes to fix the empty graphics and this should address this issue in a way that is even better for the user. Thus, this issue is being closed.
