### ISSUE TITLE
Replace checks with strings in CSV Pipeline validation 

### ISSUE THREAD

**Issue by lindavin** [OpenEnergyDashboard/OED#640]
### Is your feature request related to a problem? Please describe.
PR #633 will add the ability to import CSV files with or without a header row for meters and readings. In its validation stage, it first checks that the supplied parameters have the appropriate values, and then sets default values for missing parameters using strings such as `'true', 'false'`. A developer might think that default values were set as booleans and forget that they were actually set as strings. I have made this mistake before.

### Describe the solution you'd like

The default values are located at the top of the `/src/server/services/csvPipeline/validateCsvUploadParams`. It would be helpful to change the default string values of `'true'`, `'false'` to the equivalent boolean values. This would require changing checks like
```javascript
if (refreshReadings === 'true'){
...
}
```
to
```javascript
if (refreshReadings){
...
}
```
### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by huss** [comment]
The logic for this (and src/server/services/csvPipeline/uploadReadings.js, etc.) is now changed so it uses BooleanTypesJS. These are still strings but I think it is harder to make the mistake. They also now involved three values. Given all of this I am closing this issue.
