### ISSUE TITLE
Meter-by-meter logic for serving compressed data

### ISSUE THREAD

**Issue by lindavin** [OpenEnergyDashboard/OED#665]
### Is your feature request related to a problem? Please describe.

Fictitious data is displayed when the underlying reading data has a lower reading frequency than the frequency that the compressed readings algorithm tries to serve. For example, if the compression algorithm tries to serve data from the now materialized hourly view when the underlying data is 4-hourly data. This compression serves fictitious data because there is not actually any hourly data; instead a constant or linear approximation is applied. As the algorithm is now the only "true" compressed data would be from the daily view.

### Describe the solution you'd like

One idea to resolve this would be to track the reading frequency onto the meter as a new column. This could either be provided from the administrators when they first create the meters or be estimated from the first batch of readings from the data. Then the compression algorithm would determine the appropriate level of compression for serving data for certain time intervals.

### Describe alternatives you've considered

OED does not indicate whether the data displayed is compressed or not. We could instead visually indicate the level of compression to the user when they read the graph. This would be less misleading since they should also know the actual reading rate of the meter and understand that the compression is not displaying real data. 

### Additional context
With the addition of PR #660 this only becomes an issue if the meter reads slower than 1 reading per hour. For electricity, this is less of an issue since most meters read data every 15-minutes. As OED generalizes this might become an issue for certain energy sources.

**Comment by huss** [comment]
I note that #594 proposes to add ranges to each point. This relates to the idea of telling whether the underlying data has an averaging as the ranges are only interesting in these cases.

During discussions of tracking reading frequency on each meters a few items came up. First, what should be done if there meters/groups with different frequency of reading? OED could use the least frequent points for all meters/groups to guarantee no issues in number of points and all lines lines are consistent. Another option is for each meter/group to use the optimal level. This would get the best resolution for each line but they would differ. It also means OED cannot automatically get all the meters & groups at the same time. Batching based on which ones are the same type of underlying readings to graph would allow those to be batched and make the DB requests go faster. Second, how should a group be handled? The underlying meters may have different frequencies so summing the values raises issues about where each point should be, esp. when looking at the raw readings data.

I'm sure there are other considerations to think through before going forward with this.

**Comment by huss** [comment]
Just found issue #599 has one point on exporting raw group data. This relates to this issue.

Also, @lindavin and I have had some discussion of this. We need to flush out ideas given all the considerations.
