### ISSUE TITLE
further Obvius testing

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#673]
### Is your feature request related to a problem? Please describe.

We should have tests to verify that Obvius uploads store the correct information in the database.

### Describe the solution you'd like

src/server/test/db/configfileTests.js makes sure the parsing of an Obvius configuration file is correct. However, it does not verify that an actual upload puts the correct data into the database. It should create a meter with the correct name, type, note, etc.

src/server/test/db/loadLogfileToReadingsTests.js similarly checks the parsing and some DB info but not that the loaded readings are correct.

### Describe alternatives you've considered

Manually testing was recently done but this is not the correct long-term solution. We missed a bug in OED from a lack of automated tests.

### Additional context

@huss can help a developer understand what should happen. Looking at the database after an upload will also show what is expected.

**Comment by BrendenHaskins** [comment]
My team is interested in working on this issue. How can I connect for more information?

**Comment by huss** [comment]
@BrendenHaskins Thanks for inquiring about this issue.  It has been a while since I thought about this but am glad it may move forward. I've assigned it to you to hold it. Would it be possible to do a video call via Discord to discuss this? You can message me on the OED Discord server (see contact info on OED Website for our Discord server). If that is an issue or you want to do it another way then just add to this comment.
