### ISSUE TITLE
enhance loading meter timezone

### ISSUE THREAD

**Issue by truongdd03** [OpenEnergyDashboard/OED#681]
### Describe the bug

Each time the meters page loads, the timezone of each meter is fetched separately, taking a lot of requests. This makes the rate limit in PR #676 high, which is very risky. Optimization is needed to reduce the number of requests

### To Reproduce

1. Click the "Meters" button
2. Look at the Docker console window, you will see the timezones requests starting with "GET /api/timezones"

### Expected behavior

The number of timezones requests is reduced.

**Comment by huss** [comment]
A sample terminal output is:

oed-web-1       | GET /api/version 200 0.830 ms - 8
oed-web-1       | GET /api/version 304 1.262 ms - -
oed-web-1       | POST /api/login/ 200 125.587 ms - 194
oed-web-1       | GET /api/version 304 0.928 ms - -
oed-web-1       | POST /api/verification 200 8.406 ms - 16
oed-web-1       | GET /api/meters 200 18.358 ms - 7920
oed-web-1       | GET /api/version 304 0.254 ms - -
oed-web-1       | GET /api/timezones 304 391.689 ms - -
oed-web-1       | GET /api/timezones 200 392.554 ms - 74132
oed-web-1       | GET /api/timezones 200 493.675 ms - 74132
oed-web-1       | GET /api/timezones 200 557.813 ms - 74132
oed-web-1       | GET /api/timezones 200 590.012 ms - 74132
oed-web-1       | GET /api/timezones 200 896.451 ms - 74132
oed-web-1       | GET /api/timezones 200 831.520 ms - 74132
oed-web-1       | GET /api/timezones 200 641.986 ms - 74132
oed-web-1       | GET /api/timezones 200 864.115 ms - 74132
oed-web-1       | GET /api/timezones 200 337.377 ms - 74132
oed-web-1       | GET /api/timezones 200 1032.304 ms - 74132
oed-web-1       | GET /api/timezones 200 486.129 ms - 74132
oed-web-1       | GET /api/timezones 200 398.879 ms - 74132
oed-web-1       | GET /api/timezones 200 610.495 ms - 74132

When you have a lot of meters you can see the delay in setting this value for each one on initial load.

**Comment by Jake-Bodin** [comment]
I would like to work on this
