### ISSUE TITLE
failure if no map file chosen or no name on creation

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#686]
### Describe the bug

If you go to the map creation page and enter a name and angle but do not select a map then when you Save and continue you get a blank page. You cannot easily get off this page.

Similarly, if you create a map but do not give it a name, it will fail. However, this will allow you to get through the entire calibration step but gives a failure message when you try to save to the database at the end of the calibration.

### To Reproduce

See above.

### Expected behavior

OED should give an error popup (as it does for a missing or invalid angle) during the map creation step to force the user to input all the needed information.

### Additional context

None.

**Comment by nathang15** [comment]
I want to work on this issue.
