### ISSUE TITLE
Possibly moving to @chakra-ui/slider

### ISSUE THREAD

**Issue by jina2k** [OpenEnergyDashboard/OED#719]
### Is your feature request related to a problem? Please describe.

rc-slider's documentation is very confusing, and doesn't seem very intuitive in general. Upon trying to fix an issue in #715 , I found the documentation to be lacking, where websites that were linked provided incomplete source code due to the site's UI.

### Describe the solution you'd like

Instead, I propose moving to @chakra-ui/slider if issues occur when updating the slider. After fixing the issue, it's possible this isn't necessary, but @chakra-ui/slider makes separating components of the slider much cleaner in my opinion. If another package comes out by the time there are issues with rc-slider, we can move to a different package instead. 

### Describe alternatives you've considered

There's also the possibility of removing the slider in general, or at least providing an additional text box to input custom days. 

### Additional context

https://chakra-ui.com/docs/form/slider for more documentation

**Comment by huss** [comment]
PR #1249 got rid of the slider so this is now obsolete. That PR also notes that the slider docs seemed off/difficult.
