### ISSUE TITLE
Normalize Readings

### ISSUE THREAD

**Issue by LucasFares** [OpenEnergyDashboard/OED#74]
We need to be able to compare and normalize readings in order to support things like competitions between buildings or to compare energy usage from different periods in time.

**Comment by LeoTindall** [comment]
Probably blocked on #104 ?

**Comment by johndiiorio** [comment]
Comparing was implemented with PR #140

**Comment by LucasFares** [comment]
Compare has been implemented and normalization is being implemented in issue #209.
