### ISSUE TITLE
Giving warnings when setting displayable to false (groups)

### ISSUE THREAD

**Issue by jina2k** [OpenEnergyDashboard/OED#743]
### Is your feature request related to a problem? Please describe.

There are cases where if you set a meter to be non-displayable, but a group containing this meter to be displayable, the group would be allowed to show its readings when graphing onto a line/bar/etc. This is accounted for and hidden away in the groups page, but the readings can be retrieved. 

### Describe the solution you'd like

We should give warnings to administrators such that we would recursively check everytime we edit a meter to be non-displayable (in addition to groups) where it would search all groups affected and to notify the user that this would expose hidden meters/groups. 

### Describe alternatives you've considered

We could also set displayable so that if group's displayable is set to true, all meter/groups inside that group are set to displayable and cannot be changed until you set the group's displayable to false.

### Additional context

This is something that should be included in the Resource Generalization board where work is being done to recursively check other aspects of the application. Using the same algorithm and applying this change would be ideal.

**Comment by Jake-Bodin** [comment]
I would like to work on this

**Comment by huss** [comment]
After talking about this, I think it should only warn if the group is also displayable.

**Comment by danielshid** [comment]
I would like to work on this issue.
