### ISSUE TITLE
fix JSDoc in code base

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#769]
### Is your feature request related to a problem? Please describe.

PR #767 added the ability to run JSDoc linting on the code. When enabled, it finds a lot of issues with the current documentation. We cannot turn this check on until the issues are resolved.

### Describe the solution you'd like

We need to go through all the issues and add the needed documentation. Note anyone is welcome to work on any number of issues and it is not necessary to do them all. See .eslintrc.json for two lines to uncomment to get the checks to happen when you run 'npm run check'.

### Describe alternatives you've considered

We continue to have substandard documentation.

### Additional context

Documentation is awesome :-)

**Comment by spearec** [comment]
I have currently fixed all existing jsdoc errors in my local branch (https://github.com/spearec/OED/tree/jsdoc). After some discussion with @huss, these changes will possibly be folded into some other changes to which ESLint packages OED uses. This will probably happen during the 1.0 release phase, as it is easier to make this transition on a frozen codebase.

In the meantime, please make sure to add jsdoc comments to any new functions you create, as this will minimize the migration process for this issue.
