### ISSUE TITLE
change refresh readings string

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#792]
### Is your feature request related to a problem? Please describe.

The current CSV reading page says "Refresh Readings". But to be consistent with the newer hourly refresh, it should say "Refresh Daily Readings".

### Describe the solution you'd like

Change data.js for the name of this string and change translation.

### Describe alternatives you've considered

Don't update.

### Additional context

NA

**Comment by Mushmou** [comment]
Hello Team L from CTI would like to work on this issue.
