### ISSUE TITLE
lost help on pages with cards

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#794]
### Describe the bug

If you are on one of the new pages that uses modals (unit, meter, conversion) then the help icon works fine when you first load the page. However, once you have a modal popup (edit or create) then it will not work until you leave the page and return. The help on the modal popup works fine.

### To Reproduce

1. To to one of the modal pages.
2. Click the help icon to see it works.
3. Click to edit or create a new item.
4. After the modal pops up you can see the help works. You don't need to actually change anything on the page. Leave the popup in any way.
5. The help icon on the card page will not work.
6. Go to any other page and return and the help icon now works.

### Expected behavior

The help icons should always work.

### Additional context

None

**Comment by Donny-Guo** [comment]
I am working on this issue along with Conlyn and Oscar.
