### ISSUE TITLE
line graph links don't work

### ISSUE THREAD

**Issue by spearec** [OpenEnergyDashboard/OED#813]
### Describe the bug

Line chart links do not work. This seems to be caused by some issue with units being improperly initialized when OED parses the link.

### To Reproduce

1. Toggle chart link
2. Copy line graph link
3. paste into browser
4. Blank page appears

### Expected behavior

The link should initialize the graph properly.

### Screenshots

![image](https://user-images.githubusercontent.com/113216142/200072782-44ef60e7-b13c-456f-b7f9-b45a09dc1629.png)

### Machine info (please complete the following information)

 - OS: Windows
 - Browser & Version Chrome
 - OED Version 0.8.0

**Comment by huss** [comment]
Thank you for reporting this. This is part of the work on resource generalization. Sorry we did not create issues for all the items being worked on. There is a team that is looking into fixing this per the design document and I've assigned them to this issue.
