### ISSUE TITLE
React hooks for line, bar, compare & map graphics pages

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#888]
### Is your feature request related to a problem? Please describe.

Please see issue #726 for information.

### Describe the solution you'd like

The graphic pages located in files src/client/app/containers/LineChartContainer.ts, src/client/app/containers/BarChartContainer.ts, src/client/app/containers/CompareChartContainer.ts & src/client/app/containers/MapChartContainer.ts need to be updated for React hooks. The look of the page will stay the same.

Note that each of the Containers interacts with react-plotly using the old style mapStateToProps. Information on a way to just use a Component is available. Some useful links may be [react-plotly README](https://github.com/plotly/react-plotly.js/blob/master/README.md) and React [Plotly information page](https://plotly.com/javascript/react/). Many other help pages are available.

### Additional context

src/client/app/components/DashboardComponent.tsx is part of another issue but changes may be needed.

**Comment by ChrisMart21** [comment]
#1113 Addresses All other than compare which still has a mapStateToProps container.

**Comment by huss** [comment]
Replaced with issue #1195 for last part.
