### ISSUE TITLE
React hooks for main containers (dashboard, footer, header, route)

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#893]
### Is your feature request related to a problem? Please describe.

Please see issue #726 for information.

### Describe the solution you'd like

This transitions a number of components where the code located in files src/client/app/components/DashboardComponent.tsx, src/client/app/containers/DashboardContainer.ts, src/client/app/components/FooterComponent.tsx, src/client/app/containers/FooterContainer.ts, src/client/app/components/HeaderComponent.tsx, src/client/app/containers/HeaderContainer.ts, src/client/app/components/RouteComponent.tsx & src/client/app/containers/RouteContainer.ts need to be updated for React hooks. The look of each item will stay the same.

### Additional context

It is hoped that other pages do not need to be changed as part of this but these are used across the OED React code base.

**Comment by spearec** [comment]
#958 converts HeaderComponent to use hooks

**Comment by huss** [comment]
Fixed by PR #1113 so closing.
