### ISSUE TITLE
hide rate menu when not applicable

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#899]
### Is your feature request related to a problem? Please describe.

OED has introduced a rate menu on the line graphic page. It does not apply for these line choices:

- When the units is of raw type.
- When displaying kW on the y-axis. This can happen because you are doing the quantity kWh or a direct graphing of kW.

### Describe the solution you'd like

The rate menu should automatically disappear when either of these line choices are active and reappear when not.

### Describe alternatives you've considered

The current situation where the menu is present but changing the choice makes no difference.

### Additional context

The Normalize by Area has logic to make it disappear/reappear for selections that do not support that option. Looking at that code may be useful. PR #885 added this and [this commit](https://github.com/OpenEnergyDashboard/OED/pull/885/commits/92d57abd6d7751cbc8843764491ef5a38308508e) should have the related code.

**Comment by nathang15** [comment]
I want to work on this issue.

**Comment by nathang15** [comment]
If I understand correctly, to fix this issue, I will need to make the rate menu options (seconds, minutes, hour, day) to be greyed out with the phrase "-----Incompatible Rates-----" above them when selecting raw type units and/or displaying kW on the y-axis. Do I understand this issue correctly?

If it is possible, may I ask besides temperature, are there any other types of raw units that OED use? 

Thank you!

**Comment by huss** [comment]
> If I understand correctly, to fix this issue, I will need to make the rate menu options (seconds, minutes, hour, day) to be greyed out with the phrase "-----Incompatible Rates-----" above them when selecting raw type units and/or displaying kW on the y-axis. Do I understand this issue correctly?

What is actually desired is that the rate drop down menu is not displayed in these circumstances. There is not a change to the meter/group or other menus. A less dynamic example of this is the fact that the compare or map graphic does not have the export buttons. In The following figure the rate menu is in red and mostly invisible but in the final look it would not be taking up any space. Does this help?

![Screenshot 2023-09-17 162214](https://github.com/OpenEnergyDashboard/OED/assets/987062/64ff9cbc-8e19-4775-bac9-3d81e7df8383)
 
> If it is poss
ible, may I ask besides temperature, are there any other types of raw units that OED use?

A site can define any units it wants to use so it is possible to have other raw units. Temperature is probably the most common one that would be used but we cannot assume it is the only one. Thus, the type of a unit should be checked and not the name of the unit for raw. The y-axis label can probably be used to figure out if it is graphing in kW.

Thanks for asking for clarification.

**Comment by nathang15** [comment]
So, if I understand correctly, if the user inputs an incompatible option, the rate menu should disappear, including the title and the tooltip?

Thank you for your clarification

**Comment by huss** [comment]
> So, if I understand correctly, if the user inputs an incompatible option, the rate menu should disappear, including the title and the tooltip?

Yes, I think that is what we want.
