### ISSUE TITLE
reducing options on pages with modal

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#900]
### Is your feature request related to a problem? Please describe.

Basically, OED wants to move some of the options shown to a modal to focus on the most used/important options. This should help improve the UI.

### Describe the solution you'd like

This is discussed in the [fewer options design doc](https://github.com/OpenEnergyDashboard/DesignDocs/blob/main/simplifyOptions/fewerOptions.md).

### Describe alternatives you've considered

Don't make the change.

### Additional context

None

**Comment by 25tallurich** [comment]
I would like to work on this.

**Comment by nlin21** [comment]
I will work on this
