### ISSUE TITLE
convert from pik array to cik state

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#901]
### Is your feature request related to a problem? Please describe.

For a variety of reasons, convert from a pik array to cik state on client-side. See the [pikState.md](https://github.com/OpenEnergyDashboard/DesignDocs/blob/main/pikState.md) design document.

### Describe the solution you'd like

See design document.

### Describe alternatives you've considered

We would have to change the proposed way of doing baselining on client-side.

### Additional context

NA

**Comment by qnhn22** [comment]
I would like to work on this issue. Thank you!
