### ISSUE TITLE
make conversion menus dynamic

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#904]
### Is your feature request related to a problem? Please describe.

The conversion create page checks for a number of undesirable conditions. Most of the modal pages have React hooks to dynamically change the menus so the admin cannot make that selection. For example, once a source or destination is selected then it should be removed from the other menu. Another example is not allowing meter units to be a destination (this one is static).

### Describe the solution you'd like

Make the conversion menus use React hooks and modify menus as needed.

### Describe alternatives you've considered

The current fix of testing after selection. Many can be removed if this is done.

### Additional context

None

**Comment by qnhn22** [comment]
I would like to work on this issue. Thank you!
