### ISSUE TITLE
Mobile device support

### ISSUE THREAD

**Issue by simonbtomlinson** [OpenEnergyDashboard/OED#94]
We need first-class responsive mobile support, including placing the options for manipulating the graphs in a way that works on mobile. This is going to require some discussion about what we want the site to look like on a phone.

**Comment by LucasFares** [comment]
This is similar to issue #72.  I'm not going to remove either right now as they both involve an open pull request but this is definitely something we need to talk about.

**Comment by LeoTindall** [comment]
Now that #91 and #72 are both resolved, can we close this?

**Comment by johndiiorio** [comment]
I don't think so. Our mobile device support is still pretty awful, and could use a lot of work.

**Comment by LeoTindall** [comment]
What additional features should we add to better support mobile devices? Can they be opened as separate issues?

**Comment by huss** [comment]
A web developer has sent in the following thoughts on OED:
        Appears the graph still has usability issues when on mobile or narrow widths.
            Logo and title cover over the Options and Log In buttons.
            Graph is set to 83.33% width at all times, even at narrow widths. If working with css, try using media queries to set different CSS rules.
            Graphs shrinks to be impossible to read at narrowest widths.
            One possible fix, if working with css, would be to set a minimum width for the <div> element that wraps the content.  See attached image.  Not ideal to have horizontal scroll in web design, but reasonable perhaps when dealing with graphs which need the horizontal space to show their data.
            For line graphs, allowing users to define bounds and grouping would allow them to narrow the band and make more efficient use of the smaller space.
            For bar graphs, perhaps invert the axes on mobile if possible so that it is a horizontal bar graph, with time being in the effectively infinite vertical axis.
            For compare, put all graphs in a single column in mobile and the break into columns at widths which can display them.
