### ISSUE TITLE
cookie-parser usage

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#947]
### Is your feature request related to a problem? Please describe.

While working on PR #942, it was unclear if the package was actually used by OED. The only use is in src/server/app.js and I could not find any place that cookie was used elsewhere. OED does not seem to set any cookies. I commented it out and did not find any issues. Someone should see if it is really used (and hopefully with more knowledge of this than I have).

### Describe the solution you'd like

Remove package if not used.

### Describe alternatives you've considered

It stays in OED.

### Additional context

None

**Comment by salhernandez** [comment]
@huss I would like for this issue to be assigned to me so that the students I'm mentoring for CodeDay Labs can work on it.

**Comment by huss** [comment]
> @huss I would like for this issue to be assigned to me so that the students I'm mentoring for CodeDay Labs can work on it.

Done. I look forward to your contributions. Please let me know if you need any help.

**Comment by spearec** [comment]
@salhernandez I'm not sure if it will be related, but #958 adds a new user-specific language setting. Currently, this is set to the site default every time OED is loaded, but it could be useful to store this value in a cookie, so the user's preference is saved when they reload the site. 
Even if OED chooses to remove this package for now, it would be good to have documentation on how to add it back in if we decide we want to start using cookies.

**Comment by salhernandez** [comment]
@spearec Thanks for the info!
