### ISSUE TITLE
Move action type definitions into dedicated file

### ISSUE THREAD

**Issue by jameeters** [OpenEnergyDashboard/OED#97]
We have enough actions types now that we need to make a conscious effort to make their names distinctive. The type definitions are also creating large blocks of boilerplate at the tops of files.
Factoring out the action type definitions into a dedicated file should help with both of these issues.

**Comment by johndiiorio** [comment]
Due to the way Redux splits up the state across different reducers, I do not think this is currently needed. If this becomes a problem in the future, it can be re-opened.

**Comment by jameeters** [comment]
I'm reopening this because it will be implemented in PR #242
